# Omniprésence et anthropomorphisation des Grands Modèles de Langue dans la recherche en TAL : étude de cas exploratoire sur un corpus tiré de la conférence TALN

In [ ]:
import pandas as pd
import pickle
import spacy
import os
from spacy import displacy
from utils import return_LLM_entities_ids, return_LLM_entities_ids_en
from tqdm import tqdm
from acl_anthology import Anthology
import re

## Extraction des articles JEP-TALN-RECITAL depuis l'ACL Anthology

Dans un premier temps, on récupère les méta-données des articles JEP-TALN-RECITAL contenus dans l'ACL Anthology via la librairie [acl_anthology](https://acl-anthology.readthedocs.io/latest/guide/getting-started/).

In [2]:
# def get_year(paper):
#     try:
#         return int(re.search(re.compile(r"(19\d{2}|20[01]\d|202[0-5])"), paper.bibkey).group())
#     except:
#         return -1

# def get_paper_events(paper):
#     return [event.id for event in paper.get_events()]
    
# def get_papers_in_event(papers, event_key):
#     return [p for p in papers if event_key in get_paper_events(p)]

In [3]:
# # load the anthology
# anthology = Anthology.from_repo()

# # store all papers 
# all_papers = list(anthology.papers())
# print(len(all_papers))

# # get only JEP-TALN-RECITAL papers of years 2020-2025
# jeptalnrecital_events = ["jeptalnrecital-" + str(year) for year in range(2020, 2026)]
# jeptalnrecital_papers = []

# for event in jeptalnrecital_events:
#     jeptalnrecital_papers.extend(get_papers_in_event(all_papers, event))

# # exclude the proceeding documents to keep only articles
# for p in jeptalnrecital_papers:

#     if str(p.title).startswith("Actes de"):
#         jeptalnrecital_papers.remove(p)

    
# print(len(jeptalnrecital_papers))

On stocke les informations sur les articles identifiés dans un DataFrame pandas.

In [4]:
# data = []

# for p in jeptalnrecital_papers:
    
#     row = [
#         p.bibkey,
#         p.id,
#         p.full_id,
#         str(p.title),
#         str(p.abstract),
#         get_paper_events(p),
#         get_year(p)
#     ]

#     data.append(row)

# df = pd.DataFrame(data, columns = ["bibkey", "id", "full_id", "title", "abstract", "events", "year"])

In [5]:
data_folder = "data/"
jeptalnrecital_file_name = "jeptalnrecital-papers-VF"

# with open(os.path.join(data_folder, jeptalnrecital_file_name) + ".pkl", "wb") as f:
#     pickle.dump(df, f)

with open(os.path.join(data_folder, jeptalnrecital_file_name) + ".pkl", "rb") as f:
    df = pickle.load(f).sort_values(by = "bibkey").reset_index(drop = True)

In [6]:
df.head()

,bibkey,id,full_id,title,abstract,events,year
0,aabid-etal-2025-quand,15,2025.jeptalnrecital-coria.15,Quand les Bots Déjouent l’Apprentissage : Enje...,Identifier les bots d’une une bibliothèque num...,[jeptalnrecital-2025],2025
1,abchiche-etal-2023-integration,11,2023.jeptalnrecital-coria.11,Intégration du raisonnement numérique dans les...,"Ces dernières années, les modèles de langue on...",[jeptalnrecital-2023],2023
2,abdoulaye-ngom-etal-2025-analyse,1,2025.jeptalnrecital-coria.1,Analyse Textuelle et Extraction Géospatiale po...,L’Afrique de l’Ouest fait face à une insécurit...,[jeptalnrecital-2025],2025
3,abdul-rauf-etal-2020-simplification,33,2020.jeptalnrecital-taln.33,Simplification automatique de texte dans un co...,La simplification de textes a émergé comme un ...,[jeptalnrecital-2020],2020
4,abel-etal-2024-synthese,19,2024.jeptalnrecital-jep.19,Synthèse de gestes communicatifs via STARGATE,La synthèse de gestes lié à la parole est un d...,[jeptalnrecital-2024],2024

## Analyse spaCy et identification des mentions de LLM

Le titre et l'abstract de chaque article peuvent être identifiés par un modèle spaCy. Ceci nous permet d'exploiter les formes lemmatisées des mots ainsi que des dépendances syntaxiques (enfants) pour identifier les mentions de LLM (en complément de mots-clés).  

On utilise le modèle [https://spacy.io/models/fr#fr_dep_news_trf](https://spacy.io/models/fr#fr_dep_news_trf).

In [7]:
# model = spacy.load("fr_dep_news_trf")

In [8]:
# llm_papers_ids = []
# llm_entities_ids = []
# llm_entities = []
# docs = []

# LLM_names = ["llama", "qwen", "bert", "deepseek", "mistral", "gpt", "gemma", "gemini", "bard", "claude"]
# LLM_entities = ["ia", "llm", "llms"]

# for i, row in tqdm(df.iterrows(), total = df.shape[0]):
    
#     title = row["title"]
#     abstract = row["abstract"]

#     # concaténation titre et abstract
#     title_and_abstract = title.strip(".") + ".\n" + abstract

#     # analyse du titre et abstract, stockage des résultats pour analyses ultérieures
#     doc = model(title_and_abstract)
#     docs.append(doc)

#     # on récupère les entités dénotant des LLM pour chaque article
#     entities_ids = return_LLM_entities_ids(doc, LLM_entities, LLM_names)
#     llm_entities_ids.append(entities_ids)

#     entities = [tok.orth_ for j, tok in enumerate(doc) if j in entities_ids]
#     llm_entities.append(entities)
    
#     if len(entities_ids) > 0:
#         llm_papers_ids.append(row["full_id"])

# print(len(llm_papers_ids))

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [03:44<00:00,  3.28it/s]

271

In [9]:
# df["analyzed_text"] = docs
# df["llm_entities_ids"] = llm_entities_ids
# df["llm_entities"] = df.apply(lambda x: [tok.orth_ for i, tok in enumerate(x["analyzed_text"]) if i in x["llm_entities_ids"]], axis = 1)

In [10]:
df[df["llm_entities"].apply(lambda x : x!= [])]

,bibkey,id,full_id,title,abstract,events,year,analyzed_text,llm_entities_ids,llm_entities
1,abchiche-etal-2023-integration,11,2023.jeptalnrecital-coria.11,Intégration du raisonnement numérique dans les...,"Ces dernières années, les modèles de langue on...",[jeptalnrecital-2023],2023,"(Intégration, du, raisonnement, numérique, dan...","[6, 25, 62, 78, 92, 115, 171, 192]","[modèles, modèles, modèles, modèles, modèles, ..."
2,abdoulaye-ngom-etal-2025-analyse,1,2025.jeptalnrecital-coria.1,Analyse Textuelle et Extraction Géospatiale po...,L’Afrique de l’Ouest fait face à une insécurit...,[jeptalnrecital-2025],2025,"(Analyse, Textuelle, et, Extraction, Géospatia...","[105, 114]","[modèles, CamemBERT]"
4,abel-etal-2024-synthese,19,2024.jeptalnrecital-jep.19,Synthèse de gestes communicatifs via STARGATE,La synthèse de gestes lié à la parole est un d...,[jeptalnrecital-2024],2024,"(Synthèse, de, gestes, communicatifs, via, STA...","[45, 127]","[agents, modèle]"
10,adam-cuvillier-etal-2024-les,9,2024.jeptalnrecital-taln.9,Les représentations contextuelles stéréotypées...,Nous présentons une étude pour mieux identifie...,[jeptalnrecital-2024],2024,"(Les, représentations, contextuelles, stéréoty...","[6, 35, 105, 150]","[modèles, modèles, modèles, modèles]"
13,aguiar-etal-2025-inference,18,2025.jeptalnrecital-trad.18,Inférence en langue naturelle appliquée au rec...,Recruter des patients pour les essais clinique...,[jeptalnrecital-2025],2025,"(Inférence, en, langue, naturelle, appliquée, ...","[133, 210, 259]","[modèle, modèles, modèle]"
...,...,...,...,...,...,...,...,...,...,...
723,zanella-baril-2025-la,28,2025.jeptalnrecital-taln.28,La confiance de Mistral-7B est-elle justifiée ...,Évaluer la fiabilité des grands modèles de lan...,[jeptalnrecital-2025],2025,"(La, confiance, de, Mistral-7B, est-elle, just...","[3, 22, 26, 56, 94, 178, 209, 230]","[Mistral-7B, modèles, LLMs, Mistral-7B, Mistra..."
732,zhou-etal-2025-explicabilite,1,2025.jeptalnrecital-diagllm.1,Explicabilité par Perturbations pour les Systè...,Les systèmes de Génération Augmentée par Récup...,[jeptalnrecital-2025],2025,"(Explicabilité, par, Perturbations, pour, les,...","[26, 30, 162]","[Modèles, LLM, modèles]"
733,zhu-etal-2022-flux,2,2022.jeptalnrecital-humanum.2,Flux d’informations dans les systèmes encodeur...,Ce travail présente deux séries d’expériences ...,[jeptalnrecital-2022],2022,"(Flux, d’, informations, dans, les, systèmes, ...","[80, 86]","[modèle, modèle]"
734,zong-piwowarski-2023-xpmir,19,2023.jeptalnrecital-coria.19,XPMIR: Une bibliothèque modulaire pour l’appre...,"Ces dernières années, plusieurs librairies pou...",[jeptalnrecital-2023],2023,"(XPMIR, :, Une, bibliothèque, modulaire, pour,...","[82, 100, 116, 165]","[modèles, modèles, modèles, modèles]"
735,zong-piwowarski-2025-vers,25,2025.jeptalnrecital-coria.25,Vers un élagage de tokens sans coût dans les m...,Les modèles de RI neuronaux à interaction tard...,[jeptalnrecital-2025],2025,"(Vers, un, élagage, de, tokens, sans, coût, da...","[9, 18, 26, 175]","[modèles, modèles, ColBERT, ColBERT]"

Inspection partielle des entités identifiées comme dénotant des LLM, car des faux positifs sont possibles, par ex à cause de la chaîne  "bert" qui peut se retrouver dans des noms propres.

In [11]:
# vérification des entités LLM extraites
all_llm_entities = []

for i, row in df.iterrows():
    for e in row["llm_entities"]:
        all_llm_entities.append(e.lower())

print(sorted(list(set(all_llm_entities))))

['adminbert', 'agent', 'agents', 'albert', 'bert', 'bertalign', 'bertrand', 'bertscore', 'biobert', 'bluebert', 'camembert', 'chatgpt', 'chatgpt-4o', 'claude', 'colbert', 'deepseek', 'distilbert', 'drbert', 'etqwen2.5', 'flaubert', 'gemini', 'gemma', 'gpt', 'gpt-2', 'gpt-3', 'gpt-3.5', 'gpt-4', 'gpt-4o', 'gptscore', 'https://huggingface.co/jgmorenof/mistral_merged_0_4', 'hubert', 'ia', 'intelligence', 'intelligences', 'llama', 'llama-3', 'llama-3.3', 'llama2', 'llama3', 'llama3.0', 'llama3.1', 'llm', 'llms', 'mbert', 'mistral', 'mistral-7b', 'modèle', 'modèles', 'ollama', 'pubmedbert', 'qwen', 'roberta', 'scibert', 'selfcheckgpt']

In [12]:
from collections import Counter

c = Counter(all_llm_entities)
c

Counter({'modèles': 491,
         'modèle': 190,
         'llm': 100,
         'llms': 73,
         'bert': 62,
         'camembert': 34,
         'ia': 25,
         'agent': 16,
         'chatgpt': 15,
         'intelligence': 12,
         'agents': 8,
         'gpt': 7,
         'llama': 6,
         'flaubert': 5,
         'gpt-4o': 4,
         'hubert': 4,
         'mistral-7b': 4,
         'adminbert': 4,
         'drbert': 3,
         'gpt-2': 3,
         'qwen': 3,
         'scibert': 2,
         'roberta': 2,
         'mistral': 2,
         'claude': 2,
         'gpt-4': 2,
         'albert': 2,
         'llama3': 2,
         'llama-3': 2,
         'mbert': 2,
         'gemini': 2,
         'colbert': 2,
         'bertrand': 1,
         'biobert': 1,
         'bluebert': 1,
         'gpt-3.5': 1,
         'https://huggingface.co/jgmorenof/mistral_merged_0_4': 1,
         'bertscore': 1,
         'bertalign': 1,
         'distilbert': 1,
         'gpt-3': 1,
         'llama2': 1,
         'selfcheckgpt': 1,
         'gptscore': 1,
         'chatgpt-4o': 1,
         'llama3.0': 1,
         'llama3.1': 1,
         'etqwen2.5': 1,
         'intelligences': 1,
         'ollama': 1,
         'llama-3.3': 1,
         'deepseek': 1,
         'gemma': 1,
         'pubmedbert': 1})

In [18]:
entities_to_check = ["bertrand", "bertscore", "claude", "https://huggingface.co/jgmorenof/mistral_merged_0_4", "hubert"]

for i, row in df[df["llm_entities"].apply(lambda x: len(set([elt.lower() for elt in x]).intersection(set(entities_to_check))) > 0)].iterrows():
    print(i)
    print(row["llm_entities_ids"])
    print(row["llm_entities"])
    print(row["analyzed_text"])
    print()

117
[2, 67, 75, 78, 140, 158]
['modèles', 'modèles', 'modèles', 'HuBERT', 'modèle', 'modèles']
Adaptation de modèles auto-supervisés pour la reconnaissance de phonèmes dans la parole d’enfant.
La reconnaissance de parole d’enfant est un domaine de recherche encore peu développé en raison du manque de données et des difficultés caractéristiques de cette tâche. Après avoir exploré diverses architectures pour la RAP d’enfant dans de précédents travaux, nous nous attaquons dans cet article aux nouveaux modèles auto-supervisés. Nous comparons d’abord plusieurs modèles Wav2vec2, HuBERT et WavLM adaptés superficiellement à la reconnaissance de phonèmes sur parole d’enfant, et poursuivons nos expériences avec le meilleur d’entre eux, un WavLM base+. Il est ensuite adapté plus profondément en dégelant ses blocs transformer lors de l’entraînement sur parole d’enfant, ce qui améliore grandement ses performances et le fait surpasser significativement notre modèle de base, un Transformer+CTC. Enfin, nous étudions en détail les comportements de ces deux modèles en conditions réelles de notre application, et montrons que WavLM base+ est plus robuste à diverses tâches de lecture et niveaux de bruit.

167
[81, 117, 118, 131, 159]
['modèles', 'modèle', 'HuBERT', 'bert', 'modèle']
Représentation de la parole multilingue par apprentissage auto-supervisé dans un contexte subsaharien.
Les approches auto-supervisées ont conduit à des avancées majeures dans le domaine de l’apprentissage profond. Par l’exploitation d’une grande quantité de données non annotées, ces approches ont notamment permis des améliorations dans des contextes peu dotés. Toutefois, les langues africaines restent majoritairement sous-représentées dans les jeux de données de préentraînement publiquement distribués. Dans ces travaux, nous préentraînons des modèles de parole auto-supervisés multilingues à partir de langues subsahariennes exclusivement. Nous étudions la pertinence des représentations apprises sur la tâche de reconnaissance de parole, en utilisant le jeu d’évaluation FLEURS-102. Notre modèle HuBERT Base obtient des résultats similaires face à l’approche multilingue w2v-bert de FLEURS, tout en étant plus efficient, avec 6 fois moins de paramètres et 7 fois moins de données. Nous présentont aussi un second modèle exploitant une sous-sélection équilibrée des données initiales, obtenant des performances compétitives avec près de 80 fois moins de données de préentraînement.

168
[87]
['Hubert']
Étude en temps réel de la fusion des /a/ ~ /ɑ/ en français depuis 1925.
Cette étude explore la variation diachronique de la réalisation des voyelles /a/ ~ /ɑ/ du français en position finale de mot dans la parole déclamatoire/journalistique de 1925 à 2023. Nos données comprennent deux corpus préexistants – le corpus d’archives INA (1940–1997) et le corpus ESTER (2000–2004) – ainsi que deux nouveaux corpus composés d’enregistrements issus des Archives de la Parole d’Hubert Pernot (1925–1929), de Radio France et de YouTube (2020–2023).Nos résultats indiquent une postériorisation du /a/ vers une position plus centrale et, dans une moindre mesure, une antériorisations du /ɑ/, qui ont abouti à la neutralisation et la fusion acoustique des deux phonèmes au cours du XXe siècle. Les résultats sont discutés à la lumière de l’évolution globale du système des voyelles à double timbre en français.

185
[94]
['Bertrand']
C’est “mm-hm, oui” ou “mm-hm, non” ? Propositions pour une grammaire des composantes acoustiques des interactions nasalisées (A modest proposal for the pragmatic of nasal grunts in the CID corpus).
Cet article se propose d’envisager l’existence d’une grammaire spécifique aux interactions nasalisées (Chlébowski et Ballier, 2015). Notre proposition se fonde sur une annotation des composantes acoustiques de cette sous-catégorie de sons non-lexicaux (Ward, 2006) dans le corpus CID (Bertrand et al., 2008). Nous voudrions présenter les contraintes combinatoires et régularités qui semblent s’appliquer à ces composantes acoustiques, ainsi que discuter leur structuration. Les résultats préliminaires de l’analyse des composantes acoustiques semblent suggérer des plages de valeurs par défaut pour les réalisations des IN (notamment pour la durée). La violation de ces usages peut donner lieu à une analyse de type gricienne d’implicature.

220
[122, 133, 147, 159, 172]
['modèle', 'modèles', 'modèles', 'Claude', 'Claude']
GeNRe : un système de neutralisation automatique du genre exploitant les noms collectifs.
Les outils de traitement automatique des langues (TAL) ont tendance à introduire des biais de genre, notamment par une surutilisation du masculin générique. La tâche de réécriture du genre en TAL, qui vise à remplacer des formes genrées par des formes neutres, inclusives ou contraires, peut permettre de réduire ces biais. Bien que des travaux de neutralisation automatique du genre aient été conduits en anglais, aucun projet similaire n’existe pour le français. Cet article présente GeNRe, le tout premier système de neutralisation automatique du genre, qui exploite les noms collectifs. Nous présentons un modèle à base de règles (SBR) et affinons deux modèles de langue à partir des données générées. Nous nous intéressons aussi aux modèles d’instruction, jusque-là inutilisés pour cette tâche, en particulier Claude 3 Opus. Nous obtenons des résultats similaires pour le SBR et Claude 3 Opus lorsqu’il est utilisé conjointement avec notre dictionnaire.

286
[5, 28, 33, 51, 130, 135, 171, 187, 212, 248, 260, 299, 304]
['modèles', 'modèles', 'LLM', 'modèles', 'modèles', 'LLM', 'LLM', 'modèle', 'LLM', 'modèles', 'modèles', 'modèle', 'https://huggingface.co/Jgmorenof/mistral_merged_0_4']
PatientDx : Fusion des grands modèles de langue pour la protection de la confidentialité des données dans le domaine de la santé.
L’affinage des grands modèles de langue (abrégé LLM de l’anglais large language model) est devenu la pratique courante pour améliorer la performance des modèles sur une tâche donnée. Cependant, cette amélioration de performance s’accompagne d’un coût : l’entraînement sur de vastes quantités de données annotées potentiellement sensibles, ce qui soulève d’importantes préoccupations en matière de confidentialité des données. Le domaine de la santé constitue l’un des domaines les plus sensibles exposés aux problèmes de confidentialité des données. Dans cet article, nous présentons “PatientDx”, une architecture de fusion de modèles permettant de concevoir des LLM efficaces pour les tâches prédictives en santé sans nécessiter d’affinage ni d’adaptation sur les données des patients. Notre proposition repose sur des techniques récemment proposées connues sous le nom de fusion de LLM et vise à optimiser une stratégie de fusion modulaire. “PatientDx” utilise un modèle pivot adapté au raisonnement numérique et ajuste les hyperparamètres sur des exemples en fonction d’une métrique de performance, mais sans entraîner le LLM sur ces données. Les expériences utilisant les tâches de prédiction de mortalité de l’ensemble de données MIMIC-IV montrent des améliorations jusqu’à 7% en termes d’AUROC par rapport aux modèles initiaux. De plus, nous confirmons que, comparée aux modèles affinés, notre proposition est moins sujette aux problèmes de fuite de données sans nuire à la performance. Enfin, nous démontrons qualitativement les capacités de notre proposition à travers une étude de cas. Notre meilleur modèle est publiquement disponible : https://huggingface.co/Jgmorenof/mistral_merged_0_4. Ceci est le résumé de l’article publié “PatientDx : Merging Large Language Models for Protecting Data-Privacy in Healthcare” dans l’atelier CL4Health, NAACL 2025 (Moreno et al., 2025).

376
[34]
['BERTScore']
Identification de mesures d’évaluation fiables pour la révision de textes scientifiques.
L’évaluation de la révision des textes scientifiques reste un défi, car les métriques traditionnelles telles que ROUGE et BERTScore se concentrent sur la similarité à une référence plutôt que sur les améliorations réalisées. Nous analysons et identifions les limites de ces métriques et explorons des méthodes d’évaluation alternatives qui s’alignent mieux sur le jugement humain. Nous évaluons d’abord manuellement différentes révisions pour estimer leur qualité. Ensuite, nous examinons la possibilité d’utiliser des métriques d’évaluation sans référence provenant de domaines connexes du traitement automatique des langues (TAL) ainsi que des approches GML en tant que juge. Nos résultats montrent que GMLs évaluent efficacement le suivi des instructions mais peinent à évaluer l’acceptabilité, alors que les métriques spécifiques au domaine fournissent des informations complémentaires. Nous recommandons une approche hybride combinant l’évaluation GML en tant que juge et les mesures spécifiques à la tâche offrant l’évaluation la plus fiable de la qualité de la révision.

433
[290]
['Hubert']
muDialBot, vers l’interaction humain-robot multimodale pro-active.
Dans le projet ANR muDialBot, notre ambition est d’incorporer pro-activement des traits de comportements humains dans la communication parlée. Nous projetons d’atteindre une nouvelle étape de l’exploitation de l’information riche fournie par les flux de données audio et visuelles venant des humains. En particulier en extraire des événements verbaux et non-verbaux devra permettre d’accroître les capacités de décision des robots afin de gérer les tours de parole plus naturellement et aussi de pouvoir basculer d’interactions de groupe à des dialogues en face-à-face selon la situation. Récemment on a vu croître l’intérêt pour les robots compagnons capable d’assister les individus dans leur vie quotidienne et de communiquer efficacement avec eux. Ces robots sont perçus comme des entités sociales et leur pertinence pour la santé et le bien-être psychologique a été mise en avant dans des études. Les patients, leurs familles et les professionels de santé pourront mieux apprécier le potentiel de ces robots, dans la mesure où certaines limites seront rapidement affranchies, telles leur capacité de mouvement, vision et écoute afin de communiquer naturellement avec les humains, aù-délà de ce que permettent déjà les écrans tactiles et les commandes vocales seuls. Les résultats scientifiques et technologiques du projet seront implémentés sur un robot social commercial et seront testés et validés avec plusieurs cas d’usage dans le contexte d’une unité d’hôpital de jour. Une collecte de données à grande échelle viendra compléter les test in-situ pour nourrir les recherches futures. Consoritium : LIA (porteur), INRIA Grenoble, Lab Hubert Curien, AP-HP Broca, ERM Automatismes

Correction manuelle dans le DataFrame des cas où il s'agit clairement de faux positifs :

In [23]:
# # Faux positif: 'Hubert' dans 'la parole d'Hubert Pernot'
# df.at[168, "llm_entities_ids"] = []
# df.at[168, "llm_entities"] = []

# # Faux positif: 'Betrand' dans '(Bertrand et al., 2008)'
# df.at[185, "llm_entities_ids"] = []
# df.at[185, "llm_entities"] = []

# # Faux positif: lien vers un modèle Mistral mais pas mention directe du modèle
# df.at[286, "llm_entities_ids"] = [5, 28, 33, 51, 130, 135, 171, 187, 212, 248, 260, 299]
# df.at[286, "llm_entities"] = ['modèles', 'modèles', 'LLM', 'modèles', 'modèles', 'LLM', 'LLM', 'modèle', 'LLM', 'modèles', 'modèles', 'modèle']

# # Faux positif: BERTScore est une mention de métrique et non pas de modèle
# # Remarque: 'GML' comme faux négatif, à intégrer dans future liste de mots-clés, pas ajouté ici
# df.at[376, "llm_entities_ids"] = []
# df.at[376, "llm_entities"] = []

# # Faux positif: 'Hubert' dans 'Lab Hubert Curien'
# df.at[290, "llm_entities_ids"] = []
# df.at[290, "llm_entities"] = []

In [24]:
df.loc[[168, 185, 286, 376, 290]]

,bibkey,id,full_id,title,abstract,events,year,analyzed_text,llm_entities_ids,llm_entities
168,cecelewski-etal-2024-etude,8,2024.jeptalnrecital-jep.8,Étude en temps réel de la fusion des /a/ ~ /ɑ/...,Cette étude explore la variation diachronique ...,[jeptalnrecital-2024],2024,"(Étude, en, temps, réel, de, la, fusion, des, ...",[],[]
185,chlebowski-ballier-2020-cest,12,2020.jeptalnrecital-jep.12,"C’est “mm-hm, oui” ou “mm-hm, non” ? Propositi...",Cet article se propose d’envisager l’existence...,[jeptalnrecital-2020],2020,"(C’, est, “, mm, -, hm, ,, oui, ”, ou, “, mm, ...",[],[]
286,g-moreno-etal-2025-patientdx,22,2025.jeptalnrecital-trad.22,PatientDx : Fusion des grands modèles de langu...,L’affinage des grands modèles de langue (abrég...,[jeptalnrecital-2025],2025,"(PatientDx, :, Fusion, des, grands, modèles, d...","[5, 28, 33, 51, 130, 135, 171, 187, 212, 248, ...","[modèles, modèles, LLM, modèles, modèles, LLM,..."
376,jourdan-etal-2025-identification,25,2025.jeptalnrecital-taln.25,Identification de mesures d’évaluation fiables...,L’évaluation de la révision des textes scienti...,[jeptalnrecital-2025],2025,"(Identification, de, mesures, d’, évaluation, ...",[],[]
290,gallienne-poibeau-2023-quelques,1,2023.jeptalnrecital-statement.1,Quelques observations sur la notion de biais d...,Cet article revient sur la notion de biais dan...,[jeptalnrecital-2023],2023,"(Quelques, observations, sur, la, notion, de, ...",[],[]

In [25]:
df[df["llm_entities"].apply(lambda x : x!= [])].shape[0]

267

In [26]:
processed_jeptalnrecital_file_path = "analyzed-jeptalnrecital-papers"

# with open(os.path.join(data_folder, processed_jeptalnrecital_file_path) + ".pkl", "wb") as f:
#     pickle.dump(df, f)

with open(os.path.join(data_folder, processed_jeptalnrecital_file_path) + ".pkl", "rb") as f:
    df = pickle.load(f)

## Extraction de structures syntaxiques

Selon relations de dépendances syntaxiques UD ([https://universaldependencies.org/u/dep/index.html](https://universaldependencies.org/u/dep/index.html)).

In [30]:
def get_token_idx(token, doc):
    idx = -1
    for i, tok in enumerate(doc):
        if tok == token:
            idx = i
    return idx

### Entités-LLM en position de sujet verbal

_POS=VERB --nsubj--> E

In [35]:
all_verbs_tokens = []

for i, row in tqdm(df.iterrows(), total = df.shape[0]):

    # accès à la position des entités LLM et au texte analysé
    llm_entities_ids = row["llm_entities_ids"]
    doc = row["analyzed_text"]
    verbs = []
    
    for e_id in llm_entities_ids:
        
        tok = doc[e_id]
        deprel = tok.dep_
        head = tok.head
        
        # relation 'nsubj' entre un verbe et l'entité-LLM
        if deprel == "nsubj" and head.pos_ == "VERB":

            head_id = get_token_idx(head, doc)
            verbs.append((e_id, head_id))
            verb = head.lemma_
            
            # relation 'expl' indique présence de pronoms réflexifs
            # par ex : 's'appuyer'
            head_expl_children = [child for child in head.children if child.dep_.startswith("expl")]
            if len(head_expl_children) > 0:
                verb = "(" +head_expl_children[0].orth_ + ") " + verb


            # relation 'xcomp' indique un complément verbal
            # par ex : 'pouvoir prédire'
            head_xcomp_children = [child for child in head.children if child.dep_ == "xcomp" and child.pos_ == "VERB"]
            if len(head_xcomp_children) > 0:
                verb = verb + " (" + head_xcomp_children[0].orth_ + ")"

            # contexte autour de l'occurrence
            print(tok, verb)
            print(doc[max(0, e_id-5) : min(e_id+20, len(doc))])
            print()

    all_verbs_tokens.append(verbs)

df["verb_subj"] = all_verbs_tokens

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 35575.22it/s]

modèles connaître
Ces dernières années, les modèles de langue ont connu une évolution galopante grâce à l’augmentation de la puissance de calcul qui a rendu

modèles parvenir (effectuer)
un paradigme courant, les modèles actuels ne parviennent pas à effectuer des calculs de manière satisfaisante. Pour y remédier, une solution est

agent recommander
objectif pédagogique donné. Un agent de renforcement, entraîné en environnement simulé, recommande des activités en maximisant la progression attendue tout en respectant

modèles permettre
locuteurs. Même si les modèles de langue les plus récents ont permis des progrès remarquables dans ce domaine, générer un résumé fidèle au

modèles améliorer
oice 16.1 démontrent que les modèles entraînés sur les clusters découverts améliorent les performances des groupes démographiques désavantagés tout en conservant des performances compétitives et

LLMs surpasser
Les résultats montrent que les LLMs surpassent largement les méthodes traditionnelles en termes de précision et de pertinence, même en configuration zero-shot

modèles permettre (résoudre)
applications. Dernièrement, les modèles neuronaux permettent de la résoudre avec de très bonnes performances. Cependant, les jeux de données permettant l’

agent pouvoir (profiter)
passée du système. Un agent conversationnel déployé au contact d’utilisateurs peut en effet profiter de retours afin d’améliorer la validité de ces

modèle rapprocher
compte le cas où le modèle de correspondance rapproche une question à une liste de réponses associées à un score de pertinence. Une approche

GPT-4o présente
ce contexte, tandis que GPT-4o, bien que produisant de meilleurs résultats, présente des signes potentiels de contamination des données.

modèles émerger
ou non), des modèles pré-entraînés tels que BERT pour l’anglais ou CamemBERT pour le français ont émergé. L’utilisation de ces

LLMs évaluer
proposons un cadre où les LLMs évaluent des critères issus de la littérature et de retours de formateurs. Nous testons trois approches : des

modèles permettre (réaliser)
caractéristiques thématiques.
Les modèles de langue pré-entraînés ont permis de réaliser des avancées significatives dans diverses tâches de traitement automatique du langage naturel

modèles introduire
entrée, tandis que les modèles hiérarchiques proposés introduisent souvent du contenu non pertinent. Nous proposons une approche de recherche d’information au niveau

modèle avoir
source et pivot, le modèle entraîné sur corpus traduit a de meilleurs résultats que la traduction séquentielle, et bien sûr que la traduction

LLM atteindre
résultats montrent que seuls les LLM fine-tunés atteignent la précision du modèle de référence. L’analyse des erreurs révèle une complémentarité des

LLMs capter
plus précise, mais les LLMs captent plus efficacement les nuances sémantiques. Ainsi, nous proposons le modèle hybride suivant : faire appel à

modèles pouvoir (avérer)
automatiquement.
Les grands modèles de langues (ou LLM, pour « large language models ») peuvent s’avérer très efficaces pour

modèle exploiter
ACE 2005 démontrent que le modèle proposé exploite correctement les informations sur les entités dans le cadre de la détection des événements et qu’il

modèles (se) révéler
language models.
Les modèles de langue pré-entraînés (MLPs) à l’instar de BERT se sont révélés remarquablement efficaces pour le classement

BERT (s’) avérer
du “transformer”, BERT s’est avéré être un modèle d’appariement sémantique efficace. Cependant, l’appariement exact reste un signal

BERT pouvoir (bénéficier)
partons de l’hypothèse que BERT pourrait bénéficier d’indices explicites d’appariement exact pour mieux s’adapter à la tâche d’estimation de pertinence

modèles prodonds
Corpora).
Les modèles de langue prodonds encodent les propriétés linguistiques et sont utilisés comme entrée pour des modèles plus spécifiques. Utiliser

modèles négliger
. De plus, ces modèles négligent souvent les informations globales sur le vocabulaire au profit d’une plus forte dépendance à l’attention.

modèles revêtir
d’origine, et les modèles qui intègrent un contrôle explicite de la longueur de sortie revêtent un intérêt particulier. Dans la continuité de

modèle obtenir
d’évaluation FLEURS-102. Notre modèle HuBERT Base obtient des résultats similaires face à l’approche multilingue w2v-bert de FLEURS, tout en

modèles générer
Generation).
Les modèles de langue génèrent des textes en prédisant successivement des distributions de probabilité pour les prochains tokens en fonction des

BERT apporter
Qu’apporte BERT à l’analyse syntaxique en constituants discontinus ? Une suite de tests pour évaluer les prédictions de structures syntaxiques

modèles favoriser
biais. Ainsi, les modèles favorisent largement la génération de masculin : le genre masculin est deux fois plus présent que le féminin en

modèles exacerber
plus en italien. Les modèles étudiés exacerbent également des stéréotypes attestés en sociologie en associant les professions stéréotypiquement féminines aux textes au féminin,

modèles présenter
langue. Cependant, ces modèles présentent et amplifient des biais stéréotypés qui peuvent mettre en danger des vies. Cette étude vise à évaluer

modèles sur-génèrer
. Nous montrons que les modèles sur-génèrent des cas décrivant des patients masculins, allant à l’encontre des prévalences réelles. Par exemple,

modèles générer
pas de genre, les modèles génèrent huit fois plus de cas cliniques décrivant des patients (plutôt que des patientes) pour les crises

modèles produire
de texte.
Les modèles de langage (LLM) produisent souvent des hallucinations lors de la génération conditionnelle de texte, introduisant des

modèles sembler (découler)
domain ).
Les modèles BERT employés en domaine spécialisé semblent tous découler d’une stratégie assez simple : utiliser le modèle BERT originel

modèles surpasser
Les résultats montrent que les modèles CamemBERT surpassent significativement les modèlesstatistiques en termes de capacité de transfert (voir Figures 1 et 2).

modèles montrer
et 2). Les modèles CamemBERT montrent une plus grande exactitude, notamment sur les ensembles de test du même média que celui utilisé

modèles afficher
dans ce média. Les modèles CamemBERT multi-médias affichent également de bonnes performances. Le modèle québécois notamment obtient les meilleurs résultats en moyenne,

modèle obtenir
de bonnes performances. Le modèle québécois notamment obtient les meilleurs résultats en moyenne, indiquant qu’une diversité de sources améliore la généricité du

modèles montrer
généricité du modèle. Les modèles statistiques (mono- et multi-médias) montrent des performances globalement inférieures, avec des variations significatives selon les médias

modèles (se) distinguer
transfert, bien que les modèles basés sur des traits se distinguent par la transparence de leur raisonnement’. Elle met également en lumière

modèles pouvoir (utilisés)
langue.
Les grands modèles de langue (LLM) peuvent être utilisés pour produire des documents synthétiques similaires à des documents réels dont

LLMs pouvoir (répondre)
LIS@DEFT’23 : les LLMs peuvent-ils répondre à des QCM ? (a) oui; (b) non; (c

modèles obtenir
Les résultats montrent que les modèles ouverts sans affinage obtiennent des performances similaires à celles d’un système supervisé fondé sur BERT, et que

modèles (se) imposer
double sens.
Les modèles de langue contextuels se sont rapidement imposés comme des outils essentiels du Traitement Automatique des Langues. Néanmoins,

modèle évaluer
questionnaire d’auto-évaluation. Un modèle de classification zéro-coup évalue la similarité entre les phrases et les réponses du questionnaire. Les résultats

modèles avoir
. Nous montrons que les modèles FlauBERT et CamemBERT pré-entraînés ont des comportements très différents même si les deux ont une tendance à générer des

modèles pouvoir (aider)
Les modèles multimodaux peuvent-ils aider à l’interprétation de cartes ? Une étude exploratoire avec GPT-4o.
Cet article

modèle devoir (accorder)
information riche à laquelle le modèle doit accorder une position préférentielle.

modèles obtenir
inconnus. Bien que des modèles récents obtiennent des résultats prometteurs, ils dépendent fortement d’hyper-paramètres dont l’ajustement nécessite des données annotées,

ChatGPT pouvoir (identifier)
Oui mais... ChatGPT peut-il identifier des entités dans des documents historiques ?.
Les modèles de langage de grande taille

agent susciter
Depuis quelques mois, l’agent conversationnel ChatGPT a suscité beaucoup d’intérêt auprès de la communauté scientifique et du grand public en raison de

modèle respecter
oeuvres de Molière. Le modèle génératif respecte la langue et le style des personnages de Molière lorsqu’il donne la réplique de l’agent

Modèles exceller
Cependant, bien que les Modèles de Langue Préentraînés (PLMs) excellent dans diverses tâches de TAL, leur efficacité dans le domaine juridique

LLM générer
la plus stable, un LLM génère des résumés modulables qui font l’objet d’une évaluation factuelle assurant leur fiabilité. Ces résumés validés

LLM affine
. Optionnellement, un second LLM affine ensuite leurs libellés pour renforcer l’interprétabilité. Expérimentée sur un corpus majeur d’incidents aériens, cette

modèles transformer
langage.
Les grands modèles de langage (LLM) pré-entraînés ont transformé le traitement du langage naturel (TALN) et les tâches

LLM hériter
issus d’internet, les LLM héritent de biais, perpétuant des stéréotypes qui peuvent fausser les représentations linguistiques et causer des préjudices représentationnels ou

LLM soutenir
domaine médical, où les LLM soutiennent la communication et la documentation, ces biais présentent des risques significatifs. Cette revue analyse les recherches

modèles démontrer
français.
Les grands modèles linguistiques (LLM) ont démontré des capacités remarquables dans diverses tâches de traitement automatique du langage naturel.

modèles traiter
mieux comprendre com- ment les modèles de langage traitent l’information stylistique, contribuant ainsi à leur interprétabilité globale. Ceci est un résumé de

CamemBERT atteindre
de classification sont testées. CamemBERT atteint jusqu’à 90 % de précision en classification binaire, suggérant un lien fort entre structure linguistique et

modèles obtenir
que, bien que les modèles génératifs obtiennent des performances prometteuses, leur qualité prédictive reste variable, et les modèles optimisés pour une tâche

modèles continuer (surpasser)
reste variable, et les modèles optimisés pour une tâche spécifique continuent de les surpasser lorsqu’ils disposent de données d’entraînement suffisantes.

modèles révolutionner
ressources.
Les grands modèles de langage (LLMs) ont révolutionné le traitement automatique des langues (TAL), mais leur succès

modèles démontrer
français.
Les grands modèles de langue (GMLs) ont démontré leur capacité à répondre correctement à des questions de médecine sur des

modèles obtenir
Ces dernières années, les modèles de langage pré-entraînés ont obtenu les meilleures performances sur un large éventail de tâches de traitement automatique du langage

modèles apparaître
de domaines généraux, des modèles spécialisés sont apparus pour traiter plus efficacement des domaines spécifiques. Dans cet article, nous proposons une étude

intelligence pouvoir (jouer)
lumière le rôle que l’intelligence artificielle, notamment les larges modèles de langage, peut jouer pour faciliter la création de corpus spécialisés.

modèle obtenir
SPLADE, nous montronsque notre modèle, lorsqu’il est combiné avec le modèle de ré-ordonnancement T5Mono, obtient desrésultats qui sont compétitifs avec ceux

modèles pouvoir (générer)
conclusions révèlent que les petits modèles peuvent générer efficacement des étiquettes et, dans certains contextes, rivaliser ou surpasser les performances de leurs homologues

modèles pouvoir (offrir)
, suggérant que les petits modèles économes en ressources peuvent offrir des solutions viables pour des défis spécifiques de classification de données

modèles montrer
littérature biomédicale. Les grands modèles de langage (LLMs) ont montré d’excellentes performances dans plusieurs tâches de compréhension et de génération du

modèles (s’) aligner
anglais. Bien que les modèles de langage s’alignent généralement sur les normes morales humaines, nous observons qu’ils restent influençables, tant

modèles avoir
études ont montré que les modèles de détection actuels ont une précision élevée, en donnant l’impression que la tâche soit résolue. Cependant

modèles résulter
résumé de réunions. Nos modèles résultent de la poursuite du pré-entraînement de deux modèles de base exclusivement sur des transcriptions de conversations et des

modèles constituer

Étant donné que les modèles de langue pré-entraînés (PLM) constituent la pierre angulaire des modèles de recherche d’informations les plus récents

modèles offrir
code.
Les grands modèles de langage (LLMs) offrent un potentiel important pour la migration de code, mais les benchmarks actuels

modèles acquérir
d’applications générales. Les modèles de langage à grande échelle acquièrent généralement ces capacités en modélisant la distribution statistique des mots par un apprentissage

IA (se) déployer
due diligence.
L’IA générative se déploie dans des secteurs à haut risque comme la santé et la finance. L’architecture RAG

modèles nécessiter
prometteurs. Cependant, ces modèles de langage nécessitent pour chaque tâche un affinement (fine-tuning) sur des données supervisées très spécifiques

modèles optimiser
un espace vectoriel. Nos modèles optimisent une fonction objectif d’apprentissage contrastif auto-supervisé sur des articles issus de la base de données bibliographique MEDLINE

modèles permettre (résoudre)
plusieurs benchmarks montrent que les modèles proposés permettent de résoudre ces tâches sans exemples (zero-shot) et sont comparables à des modèles

modèles avoir
.Par ailleurs, les modèles de langue de très grande taille (LLM) ont des performances prometteuses dans le domaine médical. Néanmoins

modèles capter
notre étude établit que les modèles de type transformers captent en grande partie la télicité et la durée.

modèles montrer
LLaMa3.
Les grands modèles de langage (LLMs) ont montré des résultats prometteurs dans diverses tâches littéraires, souvent liés la mémorisation

LLM obtenir
au 20ème siècle. Le LLM obtient des résultats impressionnants sur un corpus de 28 romans, surpassant largement les performances publiées de ChatGPT et

modèles apporter
entre langues.
Les modèles de langue pré-entraînés ont apporté des avancées significatives dans les représentations contextuelles des phrases et des mots. Cependant

modèles (se) comporter
nous montrons que de tels modèles se comportent de multiples façons sur des langues inconnues. Certaines langues bénéficient grandement de l’apprentissage par transfert

modèles connaître
Surveillance).
Les modèles de langues pré-entraînés connaissent un très grand succès en TAL, en particulier dans les situations où l’on

modèles procéder
travaux suggèrent que de tels modèles procèdent à des regroupements en langues dans l’espace latent, mais cela pourrait être dû à des biais

modèles devenir
langues.
Les grands modèles de langage deviennent la solution de choix pour de nombreuses tâches de traitement du langage naturel, y compris

modèles pouvoir (rivaliser)
que, bien que les modèles auto-régressifs utilisant des prompts puissent rivaliser en termes de reconnaissance d’entités nommées (REN) en dehors du

modèles avoir
. De plus, les modèles masqués ont un bien moindre impact environnemental que les modèles auto-régressifs. Ces résultats, cohérents dans les trois

modèles favoriser
. Nous montrons que quatre modèles de langue favorisent les énoncés qui expriment des stéréotypes dans la plupart des catégories. Nous décrivons le processus

modèles manifester
Networks).
Les modèles neuronaux de type seq2seq manifestent d’étonnantes capacités de prédiction quand ils sont entraînés sur des données de taille

modèle (s’) affirmer
particulièrement en psychologie, le modèle des Big Five, aussi appelé « OCEAN », en raison de ses cinq dimensions principales, s’

modèles sembler
nos résultats indiquent que les modèles de langue semblent en mesure de distinguer les situations émotionnelles sur la base des critères évaluatifs.

modèles encoder
Cet article explore comment les modèles de langue fondés sur les transformeurs encodent les significations compositionnelles et non-compositionnelles de séquences en anglais comme big fish

modèle différencier
Nos résultats montrent que le modèle différencie bien les deux significations, et ce dès les premières couches, avec néanmoins une variabilité selon les

modèle traire
contextuelles plus larges, le modèle ne traite pas les expressions idiomatiques comme lexicalement plus unifiées que leurs équivalents compositionnels.

modèles montrer
les tests unitaires. Les modèles prédictifs montrent que les scores des LLMs peuvent être approximés à partir des résultats des tests unitaires, et

LLM pouvoir (enrichir)
Ces résultats suggèrent que les LLM, en capturant des dimensions supplémentaires de la performance, peuvent enrichir les cadres d’évaluation éducative, offrant

LLM capturer
quantité de connaissance lexicale les LLM capturent-ils réellement afin de produire un langage aussi fluide? Pour y répondre, nous présentons ALF,

ChatGPT obtenir
14B . En moyenne, ChatGPT et la série Llama obtiennent une précision aux environs de 55%, tandis que Qwen est juste en

modèles peiner (incorporer)
texte spécialisé.
Les modèles de langue de type Transformer peinent à incorporer les modifications ayant pour but d’intégrer des formats de données

IA illustre
aux modèles existants, cette IA illustre comment nous déléguons de plus en plus notre jugement à des algorithmes perçus comme objectifs ou omniscients.

modèles constituer
du français.
Les modèles de langue préentraînés (PLM) constituent aujourd’hui de facto l’épine dorsale de la plupart des systèmes de

modèles capture
évaluer la manière dont les modèles de langue capture le sens des mots au cours de leur apprentissage. Toutefois, cette approche ne considère

modèle respecter
influencent la prédiction ? le modèle respecte t-il les axiomes connus de la RI ?) mais ne décrivent pas précisément le processus d’

modèles pouvoir (révéler)
. Nous montrons comment les modèles de langage probabilistes peuvent révéler les concepts sous-jacents en tant qu’associations fortes à plusieurs termes pour aider à

agents devenir
(LLMs), les agents conversationnels entraînés de bout en bout sans étapes explicites de prédiction de stratégie de dialogue sont devenus plus courants

modèles devoir
, suggérant que de récents modèles de langues pré-entraînés doivent être fine-tunés afin d’avoir des embeddings adéquats au niveau phrastique.

BERT pouvoir (atteindre)
tâches. Nous montrons que BERT-RQ peut atteindre des performances similaires à celles de wav2vec 2.0 tout en réduisant le temps d’apprentissage

modèle atteindre
les meilleurs résultats. Le modèle CamemBERT atteint ainsi une exactitude de 85,25% lorsqu’il est combiné avec des stratégies de gestion de données

Mistral-7B présente
. Nos résultats montrent que Mistral-7B présente une forte tendance à la surconfiance, attribuant systématiquement des scores de similarité élevés, même lorsque la

modèle continuer (surestimer)
prédits et réels, le modèle continue de surestimer systématiquement la qualité de ses réponses. Ces résultats soulignent la nécessité de mécanismes d’estimation

modèles offrir
interaction tardive.
Les modèles de RI neuronaux à interaction tardive comme ColBERT offrent un compromis compétitif entre efficacité et efficience sur de nombreuses

### Entités-LLM en position d'argument/de complément verbal

_POS=VERB --{obj, iobj, obl:arg}--> E

In [34]:
all_verbs_as_obj = set()
all_verbs_as_obj_tokens = []

for i, row in tqdm(df.iterrows(), total = df.shape[0]):
    
    llm_entities_ids = row["llm_entities_ids"]
    doc = row["analyzed_text"]
    verb_tokens = []
    
    for e_id in llm_entities_ids:
        
        tok = doc[e_id]
        deprel = tok.dep_
        head = tok.head
        
        if deprel in ["obj", "iobj", "obl:arg"] and head.pos_ == "VERB":

            # pronom réflexif attaché au verbe 
            head_expl_children = [child for child in head.children if child.dep_.startswith("expl")]
            verb = head_expl_children[0].orth_ + " " + head.lemma_ if len(head_expl_children) > 0 else head.lemma_

            # préposition attachée à l'entité
            entity_case_children = [child for child in tok.children if child.dep_ == "case"]
            verb = verb + " " + entity_case_children[0].orth_ if len(entity_case_children) > 0 else verb

            print(verb, tok)
            all_verbs_as_obj.add(verb)
            
            print(doc[e_id-5:e_id+20])
            print()

            head_id = get_token_idx(head, doc)
            verb_tokens.append((e_id, head_id))
    
    all_verbs_as_obj_tokens.append(verb_tokens)

df["verb_compl"] = all_verbs_as_obj_tokens

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 28850.91it/s]

entraîner modèles
solution est d’entraîner les modèles de langue à utiliser des outils externes tels qu’une calculatrice ou un “runtime” de code python

évaluer modèles
presse. Nous évaluons deux modèles d’extraction d’entités spatiales, GLiNER et CamemBERT, en configuration zéro-shot et après ajustement (

se refléter dans modèles
stéréotypes se reflètent dans les modèles de langue français. Nous adaptons le jeu de données StereoSet à la langue française et suivons le même

permettre au modèle
permet tout de même au modèle de langue de déterminer l’égilibilité du patient pour l’essai clinique, nous construisons la tâche Natural Language

soumettre à modèles
des amorces à plusieurs grands modèles de langue, et obtenons un score F1 compris entre 56,6 et 71,8 avec le langage patient, contre

combiner CamemBERT
, une approche hybride combinant CamemBERT et des variables linguistiques et des modèles de langue génératifs (LLMs). Une analyse approfondie de ces

utiliser LLMs
approches génératives modernes utilisant les LLMs. Les résultats montrent que les LLMs surpassent largement les méthodes traditionnelles en termes de précision et de pertinence

maintenir modèles
Une façon de maintenir ces modèles à jour pourrait être la mise à jour factuelle à l’échelle de faits atomiques. Pour étudier cette

baser sur modèles
àséquence basés sur de grands modèles de langage pré-entraînés, le choix des segments réponses à partir desquels seront générées les questions est l’un

entraîner modèle
être utilisées pour entraîner un modèle de question-réponse sur un nouveau corpus d’archives numérisées.

affecter modèles
de complexité sémantique affectant divers modèles de tailles et d’architectures différentes. En outre, nous proposons plusieurs corpus de complexité sémantique croissante dérivés

améliorer agent


entraîner modèle
sont utilisées pour entraîner le modèle sur une nouvelle tâche, est parfaitement en accord avec l’objectif de l’AA. Nous proposons d’

appliquer à modèles
elles sont appliquées à ces modèles, conduisent à des temps de calcul excessifs, ce qui empêche leur utilisation au cours d’une interaction

démythifier intelligence
pédagogiques visant à démythifier l’intelligence artificielle, en mettant en lumière ses biais et ses limitations.

s’ appuyer sur modèles
en s’appuyant sur des modèles de langue qui ont introduit une compréhension sémantique de l’organisation de la structure des documents. Les coupes

se concentrer sur modèles
se concentrer sur des petits modèles de langue (PML) avec moins de 3 milliards de paramètres et peuvent également utiliser les corpus spécifiques

surpasser modèles
Les heuristiques séquentielles surpassent les modèles hiérarchiques sur deux des trois jeux de données. démontrant l’apport du contexte ciblé.

étudier modèles
métier. Nous étudions quatre modèles de l’état de l’art, que nous commençons à évaluer avec des métriques traditionnelles. Afin de

affiner modèle
articles. Nous affinons un modèle SciBERT (Beltagy et al. , 2019) pour prédire les étiquettes restantes, que nous mettons,

construire modèles
des corpus pour construire des modèles de traduction neuronaux : une solution pour toutes les langues peu dotées ? (Corpus Translation to Build Translation

nous attaquer aux modèles
dans cet article aux nouveaux modèles auto-supervisés. Nous comparons d’abord plusieurs modèles Wav2vec2, HuBERT et WavLM adaptés superficiellement à la reconnaissance de

comparer modèles
Nous comparons d’abord plusieurs modèles Wav2vec2, HuBERT et WavLM adaptés superficiellement à la reconnaissance de phonèmes sur parole d’enfant, et poursuivons

surpasser modèle
le fait surpasser significativement notre modèle de base, un Transformer+CTC. Enfin, nous étudions en détail les comportements de ces deux modèles en

proposer modèle
Ainsi, nous proposons le modèle hybride suivant : faire appel à un LLM en cas de faible confiance en la sortie du NERL (

faire à LLM
: faire appel à un LLM en cas de faible confiance en la sortie du NERL (<0.8) selon notre propre score de

surpasser modèles
, NuNER surpasse les principaux modèles de fondation de taille comparable et a des performances similaires à celles de modèles de bien plus grande taille

améliorer modèles


améliorer modèles
la communication pour améliorer les modèles de langue pour l’analyse des émotions. Tout d’abord, nous présentons les principales théories des émotions

améliorer modèles
des pistes pour améliorer les modèles de langue pour l’analyse des émotions. Nous suggérons que ces recherches ouvrent la voie à la construction

intégrer à modèle
les mots, à un modèle convolutif pour la détection d’événements. Plus précisément, nous évaluons deux stratégies pour réaliser une telle intégration

baser sur modèle
architecture est basée sur un modèle de langage pré-entraîné et finement ajusté, où le contexte d’entrée est augmenté d’entités marquées à différents

améliorer modèle
améliore de manière significative le modèle BERT vanille de référence. Nous démontrons empiriquement l’efficacité de notre approche par le biais d’expériences exhaustives

adapter modèle
profond. Nous adaptons le modèle de langue de type Transformer T5 (Raffel et al., 2020) avec des termes médicaux et

utiliser modèle
base performant, utilisant un modèle de langue pré-entraîné. Notre méthode s’avère ainsi un moyen simple et robuste d’améliorer l’analyse vers

préentraîner modèles
travaux, nous préentraînons des modèles de parole auto-supervisés multilingues à partir de langues subsahariennes exclusivement. Nous étudions la pertinence des représentations apprises sur

présentont modèle
Nous présentont aussi un second modèle exploitant une sous-sélection équilibrée des données initiales, obtenant des performances compétitives avec près de 80 fois moins de

ré-entrainer modèle
sans nécessiter de ré-entrainer le modèle de langue. Pour cela, nous formalisons la génération sous contrainte comme un processus d’exploration d’arbre

utiliser modèles
La question d’utiliser ces modèles pour augmenter les données d’apprentissage pour des tâches d’apprentissage supervisé se pose naturellement. Dans cet article

adapter modèles
générées artificiellement en adaptant des modèles GPT-2. Les résultats montrent que les données artificielles ne sont pas encore suffisamment bonnes et nécessitent un pré-traitement

construire modèles
car il peut construire des modèles de langue à partir des corpus à analyser. L’objectif du projet couvre les points suivants : -

comparer modèles
. Nos expérimentations comparent différents modèles, dont GPT-4o mini et Mistral Moderation , sur des requêtes multilingues dans des contextes variés. Les résultats

baser sur modèle
supervisée, basée sur le modèle BERT avec prédiction de la phrase suivante, sur des conversations Reddit. La structure de Reddit nous fournit

entraîner modèle
nous permet d’entraîner notre modèle avec une fonction de perte basée sur des comparaisons plutôt que sur des valeurs numériques attendues a priori.

contenir dans modèles
géographiques contenues dans des grands modèles de langue (LLMs) : famille, taille, «quantization», «instruction fine-tuning

utiliser modèles
DEFT 2024 en utilisant des modèles de langue (LLMs) entraînés sur des données ouvertes avec moins de 3 milliards de paramètres. Les

présenter modèle
collectifs. Nous présentons un modèle à base de règles (SBR) et affinons deux modèles de langue à partir des données générées.

affiner modèles
SBR) et affinons deux modèles de langue à partir des données générées. Nous nous intéressons aussi aux modèles d’instruction, jusque-là inutilisés

nous intéresser aux modèles
Nous nous intéressons aussi aux modèles d’instruction, jusque-là inutilisés pour cette tâche, en particulier Claude 3 Opus. Nous obtenons des résultats

combiner modèles
ces méthodes en combinant plusieurs modèles et en développant une approche théoriquement fondée pour exploiter au mieux chacun d’entre eux.

évaluer modèles
flexionnelles. Nous évaluons sept modèles à l’aide de 52 000 textes en français et 2 500 textes en italien, pour la rédaction

utiliser modèles
professionnels de santé utilisent des modèles de langue. Cependant, ces modèles présentent et amplifient des biais stéréotypés qui peuvent mettre en danger des

utiliser modèles
pathologies. Nous utilisons sept modèles de langue affinés et un outil de détection automatique du genre pour mesurer les associations entre pathologie et genre

exister sur Modèles
cadre existant sur plusieurs Grands Modèles de Langue et comparons leurs performances. Nous soulignons également l’importance d’inclure des références de biais dans

affiner modèles
fidèles plausibles pour affiner les modèles par apprentissage par préférences. SCOPE pousse ainsi les modèles à préférer les sorties fidèles. Nous évaluons notre

pousse modèles
. SCOPE pousse ainsi les modèles à préférer les sorties fidèles. Nous évaluons notre approche sur divers jeux de données de génération texte-

utiliser modèle
assez simple : utiliser le modèle BERT originel comme initialisation puis poursuivre l’entraînement de celuici sur un corpus spécialisé. Il est clair que

aboutir à modèles
cette approche aboutit à des modèles plutôt performants (e.g. BioBERT (Lee et al., 2020), SciBERT (Beltagy et

entraîner modèle
de penser qu’entraîner un modèle directement sur un corpus spécialisé, en employant un vocabulaire spécialisé, puisse aboutir à des plongements mieux adaptés

entraîner modèles
hypothèse, nous entraînons des modèles BERT à partir de zéro en testant différentes configurations mêlant corpus généraux et corpus médicaux et biomédicaux. Sur

varier entre modèles
, varient considérablement entre les modèles entraînés sur différents médias. Par exemple, les éditoriaux du JDM utilisent fréquemment des points d’exclamation,

utiliser modèle
en anglais) utilisant un modèle affiné sur le corpus synthétique. Nous identifions des associations de caractéristiques cliniques qui suggèrent que le filtrage du

présente modèle

Cet article présente un modèle capable de prédire (A) si une phrase contient l’expression d’une émotion, (B)

ajuster modèles
nouvelle façon d’ajuster des modèles de langue en “Few-shot learning” se basant sur une méthode d’optimisation récemment introduite en

fonder sur BERT
un système supervisé fondé sur BERT, et que l’affinage sur les données de la tâche apporte des améliorations.

utiliser modèles
méthode permettant d’utiliser ces modèles pour ordonner un ensemble de mots cibles en fonction de leur similarité avec un mot source. Nous appliquons

injecter dans modèles
est d’injecter dans les modèles contextuels des connaissances sémantiques. Dans cet article, nous proposons une méthode pour réaliser cette injection en nous

s’ appuyer sur modèle
une s’appuyant sur un modèle de langue statique, l’autre sur un modèle contextuel. Des évaluations réalisées pour l’anglais et focalisées

enrichir modèle
permettant d’enrichir sémantiquement un modèle de type BERT sans utilisation de ressources sémantiques externes.

entraîner modèle
publications permettant d’entraîner un modèle neuronal pour la prédiction. Les approches étudiées sont : (1) la représentation de sujet par fréquence

concevoir LLM
modèles permettant de concevoir des LLM efficaces pour les tâches prédictives en santé sans nécessiter d’affinage ni d’adaptation sur les données des patients

utiliser modèle
“PatientDx” utilise un modèle pivot adapté au raisonnement numérique et ajuste les hyperparamètres sur des exemples en fonction d’une métrique de performance

entraîner LLM
, mais sans entraîner le LLM sur ces données. Les expériences utilisant les tâches de prédiction de mortalité de l’ensemble de données MIMIC

comparer aux modèles
confirmons que, comparée aux modèles affinés, notre proposition est moins sujette aux problèmes de fuite de données sans nuire à la performance.

baser sur CamemBERT
des architectures neuronales basées sur CamemBERT, nous avons comparé les performances de modèles intégrant l’information de genre à celles d’un modèle de

proposer modèle
à notre connaissance le premier modèle d’extraction de relations non-supervisé qui ne nécessite pas d’ajuster d’hyper-paramètre. Pour cela, nous adaptons

proposer modèle
Nous avons également proposé un modèle « bout-enbout », avec une première phase d’extraction d’entités nommées également basée sur un

baser sur modèles
de pointe basés sur des modèles de langage. Nos résultats indiquent plusieurs lacunes dans l’identification des entités dans le texte historique, qui

présenter agent
), nous présentons un agent conversationnel qui parle comme un personnage du théâtre de Molière. Le chatbot a été entraîné avec un modèle

combiner modèles
un cadre hybride combinant grands modèles de langage et techniques de regroupement pour extraire, résumer, évaluer et structurer automatiquement les connaissances de larges

baser sur LLM
approches récentes basées sur les LLM (G-Eval, SEval-Ex), nous mettons en évidence des écarts notables entre les

surpasser GPT-4
les jugements humains, surpassant GPT-4 (0.521) tout en maintenant l’interprétabilité et la robustesse contre l’hallucination.

repenser LLM
meilleur raisonnement – Repenser les LLM français.
Les grands modèles linguistiques (LLM) ont démontré des capacités remarquables dans diverses tâches de

utiliser modèle
connexes et utilise un grand modèle de langage (LLM) pour générer des questions complexes. Des expériences préliminaires réalisées sur 23 882 articles

demander aux LLMs
sont évalués en demandant aux LLMs de répondre à ces questions avant (i)de sélectionner les meilleures réponses et (ii)d’identifier le résumé le

affiner LLM
, nous affinons le meilleur LLM sur les résumés générés sélectionnés. Validé sur plusieurs ensembles de données, QUARTZ atteint des performances compétitives en

incorporer LLMs
conception des systèmes incorporant des LLMs. Pour ce faire, nous commençons par la définition du problème. Nous présentons ensuite les différentes méthodes

combiner modèles
proposons un cadre méthodologique combinant modèles de langage à grande échelle (LLMs) et techniques traditionnelles de traitement du langage naturel (NLP)

guide modèle
invite personnalisée qui guide un modèle de langage pour générer la revue finale. Implémenté avec le modèle T5 pré-entraîné et une stratégie de réglage

surpasser modèles
qu’il surpasse nettement les modèles de référence, surtout en génération de revues, renforçant ainsi la transparence des recommandations et la satisfaction des

utiliser modèles
nous examinons comment utiliser des modèles de langue pré-entraînés pour encoderle mot cible et son contexte, en les combinant avec des caractéristiques supplémentaires basées

exploiter BERT
BERT. Notre méthodologie exploite BERT Score pour évaluer la similarité entre les phrases des rapports générés et des transcriptions originales. Notre contribution principale

baser sur LLMs
système modulaire basé sur des LLMs guidés par du prompt engineering, tenant compte du profil cognitif de l’apprenant. Nous décrivons une stratégie

baser sur BERT
avec nos classificateurs basés sur BERT et celui sur les mesures de similarité. Notre meilleure soumission obtient une précision de 72,6 % en combinant

baser sur modèle
le classifieur basé sur un modèle CamemBERT affiné et le mécanisme d’attention croisée bidirectionnelle. Ces résultats sont proches de ceux obtenus par le

publier modèles
, nous publions les premiers modèles spécialisés pour le domaine biomédical en français, appelés DrBERT, ainsi que le plus grand corpus de données

fonder sur modèle
un classifieur fondé sur le modèle de langage pré-entraîné CamemBERT. Ces résultats préliminaires démontrent la difficulté de la tâche, avec un F-

s’ appuyer sur modèle
s’est appuyé sur un modèle de langage large de type LLaMa affiné en utilisant la méthode d’adaptation LoRA.

utiliser modèle
crowdfunding, en utilisant le modèle DistilBERT, qui a déjà été largement utilisé pour la classification de texte. En conclusion, nous discutons

pré-entraîner modèle
Nous montrons que pré-entraîner un modèle avec un corpus spécialisé, même de taille réduite, permet d’observer une amélioration des résultats. La

présenter FlauBERT
, nous présentons et partageons FlauBERT, un ensemble de modèles appris sur un corpus français hétérogène et de taille importante. Des modèles de

évaluer modèles
CNRS. Nous évaluons nos modèles de langue sur diverses tâches en français (classification de textes, paraphrase, inférence en langage naturel,

combiner avec modèle
il est combiné avec le modèle de ré-ordonnancement T5Mono, obtient desrésultats qui sont compétitifs avec ceux obtenus par les participants des campagnes d’évaluation

déployer modèles
pas de déployer entièrement les modèles neuronaux sur des documents longs pouvant contenir des milliers de mots. Trois stratégies standard ont été adoptées pour

utiliser modèles
local en utilisant soit des modèles de RI classiques, soit un module d’apprentissage, (b) l’apprentissage d’une représentation conjointe

intégrer dans modèles
intégrer ces méthodes dans les modèles récents de RI.

ajuster modèle
ajustons tout d’abord un modèle de langue pré-entraîné à l’aide d’un corpus préalablement annoté en émotions, puis nous le spécialisons sur

fonder sur Modèles
Entités Nommées fondée sur des Modèles de Langue Enrichis avec des Définitions des Types d’Entités.
Des études récentes ont identifié de nouveaux

se baser sur modèles
en se basant sur des modèles de langues pré-entraînés par enrichissement des définitions des types d’entités issus d’une base de connaissances. Les

évaluer modèles


baser sur modèles
modèles basés sur les grands modèles de langue pour supporter la recherche d’information en santé. Les jeux de données et le code sont

évaluer modèles
. Nous évaluons deux grands modèles de langue (LLMs) sur cette méthode, sur le corpus conversationnel français Paco-Cheese. Plus

utiliser modèles
classification de séquences utilisant des modèles de langage français contextualisés (Identification of patient clinical profiles : A sequence classification approach using contextualised French language

utiliser modèles
française, nous utilisons des modèles pré-entraînés avec masked language modelling et affinés à la tâche d’identification, en utilisant un corpus externe de

fonder sur BERT
plusieurs modèles monolingues fondés sur BERT (Devlin et al., 2019), notamment pour le français, a démontré l’intérêt de

tirer d’ modèle
en tirant parti d’un modèle de langage pré-entraîné afin de représenter le contenu textuel, et en enrichissant la représentation avec des entités et

combine modèles
Generation), qui combine modèles de langage (LLM) et moteurs de recherche, se distingue par sa capacité à générer des réponses

présente agent
Cet article présente un nouvel agent conversationnel intégré dans un livret de formation numérique qui relève ces défis grâce à une architecture multimodale. Notre

baser sur BERT
un composant génératif basé sur BERT. Cette approche hybride permet à la fois une représentation structurée des trajectoires d’apprentissage et des capacités d’

s’ adapter aux modèles
pertinent qui s’adapte aux modèles d’apprentissage individuels, ce qui permet une acquisition plus efficace des compétences.

utiliser modèles
proposons d’utiliser de nouveaux modèles neuronaux siamois (sentence transformers) qui plongent des textes à comparer dans un espace vectoriel. Nos modèles

exploiter modèles
plus, nous exploitons nos modèles dans la tâche de la recherche d’information biomédicale. Nous montrons que la combinaison de la méthode BM25

utiliser Modèles
cliniques en utilisant les Larges Modèles de Langue.
Dans le domaine clinique et dans d’autres domaines spécialisés, les données sont rares

entraîner modèles
des LLMs pour entraîner des modèles de moins grandes tailles mieux adaptés à notre problématique. Cette méthode donne des résultats prometteurs pour des tâches

améliorer modèles

### Adjectifs et attributs du sujet modifiants une entité-LLM

In [36]:
all_adj = set()
all_adj_ids = []

for i, row in tqdm(df.iterrows(), total = df.shape[0]):
    
    llm_entities_ids = row["llm_entities_ids"]
    doc = row["analyzed_text"]
    adj_ids = []
    
    for e_id in llm_entities_ids:
        
        tok = doc[e_id]
        deprel = tok.dep_
        children = tok.children
        head = tok.head
        
        for child in children:
            
            # Adjectifs 
            if child.dep_ == "amod" and child.pos_ == "ADJ":
                all_adj.add(child.lemma_)
                print(tok, child.orth_)
                print(doc[max(0, e_id-5):min(len(doc), e_id+15)])
                print()
                adj_id = get_token_idx(child, doc)
                adj_ids.append((e_id, adj_id))

        # Attributs du sujet
        if deprel == "nsubj" and head.pos_ == "ADJ":
            all_adj.add(head.lemma_)
            print(tok, head.orth_, "(attr)")
            print(doc[max(0, e_id-5):min(len(doc), e_id+15)])
            print()

            attr_id = get_token_idx(head, doc)
            adj_ids.append((e_id, attr_id))
    
    all_adj_ids.append(adj_ids)

df["adj_attrsubj"] = all_adj_ids

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 22797.82it/s]

modèles actuels
un paradigme courant, les modèles actuels ne parviennent pas à effectuer des calculs de manière satisfaisante. Pour y

agents conversationnels
à leur utilisation dans des agents conversationnels incarnés ou dans d’autres domaines de recherche comme la linguistique, où

modèle capable (attr)
Nous avons démontré que notre modèle est capable de générer des gestes convaincants en surpassant l’état de l’art

modèles français
stéréotypes se reflètent dans les modèles de langue français. Nous adaptons le jeu de données StereoSet à la langue

modèles français
les biais constatés dans les modèles français. De plus, nous observons que l’utilisation de corpus multilingues pour

modèles grands
des amorces à plusieurs grands modèles de langue, et obtenons un score F1 compris entre 56,6 et 71,8 avec

modèle meilleur
relativement petite pour notre meilleur modèle. Cela suggère qu’avoir le patient en tant que point de départ du

modèles génératifs
des variables linguistiques et des modèles de langue génératifs (LLMs). Une analyse approfondie de ces modèles et

modèles récents
locuteurs. Même si les modèles de langue les plus récents ont permis des progrès remarquables dans ce domaine,

intelligence artificielle
Découverte de l’intelligence artificielle par des directeurs et directrices d’école primaire : une étude de cas

intelligence artificielle
France) vis-à-vis de l’intelligence artificielle (IA), en particulier de l’IA générative, dans le

IA générative
, en particulier de l’IA générative, dans le cadre du numérique éducatif et de la transformation digitale de

modèles auto-supervisés
Vers l’entraînement de modèles de reconnaissance automatique de la parole auto-supervisés équitables sans étiquettes démographiques.
Malgré

modèles équitables
Vers l’entraînement de modèles de reconnaissance automatique de la parole auto-supervisés équitables sans étiquettes démographiques.
Malgré

modèles traditionnels
articles scientifiques: comparaison entre modèles traditionnels et modèles de langue.
L’extraction automatique des mots-clés est cruciale

modèles vectoriels
sur des statistiques et des modèles vectoriels, ainsi que des approches génératives modernes utilisant les LLMs. Les résultats

modèles neuronaux
applications. Dernièrement, les modèles neuronaux permettent de la résoudre avec de très bonnes performances. Cependant, les

Modèles Causaux
des Connaissances Factuelles dans les Modèles de Langue Causaux.
La factualité des modèles de langue se dégrade avec

modèles grands
àséquence basés sur de grands modèles de langage pré-entraînés, le choix des segments réponses à partir desquels seront générées

agent conversationnel
Améliorer un agent conversationnel : prendre en compte à la volée des retours utilisateurs (Improve a

agent conversationnel
passée du système. Un agent conversationnel déployé au contact d’utilisateurs peut en effet profiter de retours afin d’

intelligence artificielle
pédagogiques visant à démythifier l’intelligence artificielle, en mettant en lumière ses biais et ses limitations.

modèles pré-entraînés
ou non), des modèles pré-entraînés tels que BERT pour l’anglais ou CamemBERT pour le français ont émergé

modèles tels
ou non), des modèles pré-entraînés tels que BERT pour l’anglais ou CamemBERT pour le français ont émergé

modèle neuronal
0,8 est obtenue par un modèle neuronal entraîné sur des textes cliniques, écrits en français. Nous évaluons notre

modèles grandes
mais l’intégration des grandes modèles de langue (LLMs) reste peu explorée. Nous proposons un cadre où

modèles petits
se concentrer sur des petits modèles de langue (PML) avec moins de 3 milliards de paramètres et peuvent

modèles hiérarchiques
entrée, tandis que les modèles hiérarchiques proposés introduisent souvent du contenu non pertinent. Nous proposons une approche de

modèles hiérarchiques
Les heuristiques séquentielles surpassent les modèles hiérarchiques sur deux des trois jeux de données. démontrant l’apport du contexte

modèles grands
connaissances médicales pour les grands modèles de langue : Stratégies et analyse comparative.
Cet article présente une étude

modèles grands
sur l’adaptation des grands modèles de langue (LLMs) à des domaines spécialisés disposant de données limitées.

modèle généraliste
que l’adaptation d’un modèle généraliste à de nouvelles données dans le domaine médical offre des améliorations notables (

modèles génératifs
et cherchons à établir quels modèles génératifs de résumé sont les plus intéressants sur ces documents possédant de fortes spécificités

modèles intéressants (attr)
et cherchons à établir quels modèles génératifs de résumé sont les plus intéressants sur ces documents possédant de fortes spécificités

modèles neuronaux
des corpus pour construire des modèles de traduction neuronaux : une solution pour toutes les langues peu dotées ? (

modèles nouveaux
dans cet article aux nouveaux modèles auto-supervisés. Nous comparons d’abord plusieurs modèles Wav2vec2, HuBERT et WavLM adaptés

Modèles Grands
ici l’emploi de Grands Modèles de Langages (LLM) pour structurer les textes de posologie en comparant des

LLM seuls
résultats montrent que seuls les LLM fine-tunés atteignent la précision du modèle de référence. L’analyse des

LLM fine
résultats montrent que seuls les LLM fine-tunés atteignent la précision du modèle de référence. L’analyse des

modèle hybride
Ainsi, nous proposons le modèle hybride suivant : faire appel à un LLM en cas de faible confiance en

modèle suivant
Ainsi, nous proposons le modèle hybride suivant : faire appel à un LLM en cas de faible confiance en

modèles grands
automatiquement.
Les grands modèles de langues (ou LLM, pour « large language models ») peuvent

modèle compact
développement de NuNER, un modèle d’encodage du texte, compact et spécialisé dans la tâche de reconnaissance des

modèles spécialisés
partie de la famille des modèles de fondation spécialisés. L’intérêt de NuNER est qu’il ne nécessite que

modèles principaux
, NuNER surpasse les principaux modèles de fondation de taille comparable et a des performances similaires à celles de modèles

modèle convolutif
les mots, à un modèle convolutif pour la détection d’événements. Plus précisément, nous évaluons deux stratégies

Modèles Larges
l’aide de « Larges Modèles de Langue ».
Ce papier présente la participation d’EDF R&D à

modèles antérieurs
ad hoc. Contrairement aux modèles antérieurs à BERT qui nécessitent des composants neuronaux spécialisés pour capturer les différents aspects

modèles nouveaux
toujours utiles pour les nouveaux modèles contextualisés pré-entraînés tels que BERT.

modèles pré-entraînés
toujours utiles pour les nouveaux modèles contextualisés pré-entraînés tels que BERT.

modèles tels
toujours utiles pour les nouveaux modèles contextualisés pré-entraînés tels que BERT.

modèles spécifiques
utilisés comme entrée pour des modèles plus spécifiques. Utiliser leurs représentations de mots telles quelles pour des domaines peu

intelligence artificielle
de méthodes développées pour l’intelligence artificielle explicable (IAX), afin de calculer des scores d’attribution au

intelligence explicable
de méthodes développées pour l’intelligence artificielle explicable (IAX), afin de calculer des scores d’attribution au

modèles auto-supervisés
travaux, nous préentraînons des modèles de parole auto-supervisés multilingues à partir de langues subsahariennes exclusivement. Nous étudions la

modèles multilingues
travaux, nous préentraînons des modèles de parole auto-supervisés multilingues à partir de langues subsahariennes exclusivement. Nous étudions la

modèle second
Nous présentont aussi un second modèle exploitant une sous-sélection équilibrée des données initiales, obtenant des performances compétitives avec près

GPT-4o mini
comparent différents modèles, dont GPT-4o mini et Mistral Moderation , sur des requêtes multilingues dans des contextes variés.

modèles grands
géographiques contenues dans des grands modèles de langue (LLMs) : famille, taille, «quantization»,

modèles génératifs
, en particulier pour les modèles génératifs ayant des difficultés à suivre les instructions. Nos résultats montrent que la

modèle dédiés
end nécessitant un lexique et modèle de langage dédiés, il est intéressant de constater qu’une meilleure intégration dans

modèles inutilisés
Nous nous intéressons aussi aux modèles d’instruction, jusque-là inutilisés pour cette tâche, en particulier Claude 3 Opus

modèles grands
du grand public de grands modèles de langue facilite la production de contenus nuisibles, médisants, malhonnêtes ou falsifiés

modèles auto-régressifs
biais de genre dans des modèles de langue auto-régressifs.
Nous proposons un outil pour mesurer automatiquement les biais

modèles grands
textes générés par des grands modèles de langue dans des langues flexionnelles. Nous évaluons sept modèles à l’aide

modèle idéal
de la définition d’un modèle de langue « idéal » et des moyens d’y parvenir.

Modèles Grands
cadre existant sur plusieurs Grands Modèles de Langue et comparons leurs performances. Nous soulignons également l’importance d’inclure

Modèles Grands
et l’alignement des Grands Modèles de Langue (LLM) sur des questions politiques sont devenus des préoccupations cruciales

modèle originel
assez simple : utiliser le modèle BERT originel comme initialisation puis poursuivre l’entraînement de celuici sur un corpus spécialisé

modèles performants
cette approche aboutit à des modèles plutôt performants (e.g. BioBERT (Lee et al., 2020)

modèle neuronal
, 2019), un modèle neuronal pré-entraîné, et un modèle de régression logistique basé sur des traits textuels

modèles performants (attr)
entraînement. Cependant, les modèles entraînés sur Le Journal de Montréal(JDM) sont particulièrement performants même sur d’autres

modèles multi-médias
dans ce média. Les modèles CamemBERT multi-médias affichent également de bonnes performances. Le modèle québécois notamment obtient les

modèle québécois
de bonnes performances. Le modèle québécois notamment obtient les meilleurs résultats en moyenne, indiquant qu’une diversité de

modèles statistiques
généricité du modèle. Les modèles statistiques (mono- et multi-médias) montrent des performances globalement inférieures, avec des

modèles mono-
généricité du modèle. Les modèles statistiques (mono- et multi-médias) montrent des performances globalement inférieures, avec des

modèles neuronaux
étude démontre la supériorité des modèles neuronaux comme CamemBERT pour la classification de textes journalistiques, notamment grâce à leur

modèles grands
langue.
Les grands modèles de langue (LLM) peuvent être utilisés pour produire des documents synthétiques similaires

modèle capable

Cet article présente un modèle capable de prédire (A) si une phrase contient l’expression d’une

modèles gros
de cette méthode aux gros modèles de langue n’est pas triviale mais son application aux méthodes d’ajustement dites

modèles grands
DEFT 2023. Des grands modèles de langage sont amorcés avec les questions afin de collecter les réponses générées.

modèles contextuels
pour étudier les propriétés des modèles de langue contextuels mais, de manière surprenante, seules quelques-unes d’

modèles contextuels
étude des différences entre ces modèles contextuels et un modèle de plongement statique.

modèles contextuels
.
Même si les modèles de langue contextuels sont aujourd’hui dominants en traitement automatique des langues, les représentations

modèles dominants (attr)
.
Même si les modèles de langue contextuels sont aujourd’hui dominants en traitement automatique des langues, les représentations

modèles contextuels
plongements statiques à partir de modèles contextuels. Cette méthode combine la généralisation et l’agrégation des représentations contextuelles.

modèles contextuels
double sens.
Les modèles de langue contextuels se sont rapidement imposés comme des outils essentiels du Traitement Automatique

modèles anciens
vraiment sur ce plan de modèles plus anciens, comme les modèles statiques ou les modèles à base de comptes

modèles statiques
plus anciens, comme les modèles statiques ou les modèles à base de comptes. Une des façons d’améliorer

modèles contextuels
est d’injecter dans les modèles contextuels des connaissances sémantiques. Dans cet article, nous proposons une méthode pour

modèle contextuel
, l’autre sur un modèle contextuel. Des évaluations réalisées pour l’anglais et focalisées sur la similarité sémantique

modèles neuronaux
d’un nombre important de modèles de langue neuronaux affinés pour différentes tâches conduit assez naturellement à se poser la

modèle même
à partir d’un même modèle de base, de type encodeur. En considérant neuf tâches du jeu de

modèle neuronal
publications permettant d’entraîner un modèle neuronal pour la prédiction. Les approches étudiées sont : (1) la

modèle frugal
Les résultats obtenus par ce modèle frugal sont prometteurs par comparaison avec ceux d’autres grands modèles de langue.

modèles autres
avec ceux d’autres grands modèles de langue.

modèles grands
avec ceux d’autres grands modèles de langue.

modèle grand
représentations issues d’un grand modèle de langage.
Nous explorons les représentations vectorielles de la parole à partir

modèles pré-entraînés
un transformer, pour des modèles pré-entraînés et des modèles adaptés à la classification de textes. Nous montrons que

modèles grands
PatientDx : Fusion des grands modèles de langue pour la protection de la confidentialité des données dans le domaine de

modèles grands

L’affinage des grands modèles de langue (abrégé LLM de l’anglais large language model) est devenu

LLM efficaces
modèles permettant de concevoir des LLM efficaces pour les tâches prédictives en santé sans nécessiter d’affinage ni d’adaptation

modèles initiaux
d’AUROC par rapport aux modèles initiaux. De plus, nous confirmons que, comparée aux modèles affinés,

modèle meilleur
de cas. Notre meilleur modèle est publiquement disponible : https://huggingface.co/Jgmorenof/mistral_merged_0_4. Ceci est le résumé de l’article publié

modèle disponible (attr)
de cas. Notre meilleur modèle est publiquement disponible : https://huggingface.co/Jgmorenof/mistral_merged_0_4. Ceci est le résumé de l’article publié

modèles multimodaux
Les modèles multimodaux peuvent-ils aider à l’interprétation de cartes ? Une étude exploratoire avec

modèles multimodaux
évidence les limites actuelles des modèles multimodaux pour l’analyse cartographique, et souligne la nécessité de recherches fondamentales et

intelligence artificielle
équité dans les systèmes d’intelligence artificielle, nous nous intéressons aux pratiques actuelles lors des grandes campagnes d’évaluation

intelligence artificielle
Avec l’essor de l’intelligence artificielle (IA) et l’utilisation croissante des architectures d’apprentissage profond,

modèles grands
Évaluer la véracité des grands modèles de langage (LLMs) est essentiel pour de nombreuses applications. Cependant,

modèles grands
de prompts sur des grands modèles de langage. Cette tâche n’est pas seulement un défi technique, elle

modèles récents
inconnus. Bien que des modèles récents obtiennent des résultats prometteurs, ils dépendent fortement d’hyper-paramètres dont l’ajustement

modèle premier
à notre connaissance le premier modèle d’extraction de relations non-supervisé qui ne nécessite pas d’ajuster d’hyper-paramètre.

modèle non-supervisé
à notre connaissance le premier modèle d’extraction de relations non-supervisé qui ne nécessite pas d’ajuster d’hyper-paramètre.

camembert large
ont été utilisés : le camembert-large classique (run 1) et le camembert-large fine-

camembert classique
ont été utilisés : le camembert-large classique (run 1) et le camembert-large fine-

agent conversationnel
Depuis quelques mois, l’agent conversationnel ChatGPT a suscité beaucoup d’intérêt auprès de la communauté scientifique et du

modèles grands
L’évaluation fiable des grands modèles de langage (LLM) demeure un défi. Nous présentons un framework systématique

agent conversationnel
), nous présentons un agent conversationnel qui parle comme un personnage du théâtre de Molière. Le chatbot a

modèle génératif
oeuvres de Molière. Le modèle génératif respecte la langue et le style des personnages de Molière lorsqu’il donne

Modèles Préentraînés
des Signaux Contextuels Multi-niveaux des Modèles de Langue Préentraînés.
L’accès croissant aux documents juridiques sous format numérique

intelligence artificielle
droit et les chercheurs en intelligence artificielle. Cependant, bien que les Modèles de Langue Préentraînés (PLMs)

Modèles Préentraînés
Cependant, bien que les Modèles de Langue Préentraînés (PLMs) excellent dans diverses tâches de TAL, leur

modèles grands
un cadre hybride combinant grands modèles de langage et techniques de regroupement pour extraire, résumer, évaluer et structurer

LLM second
. Optionnellement, un second LLM affine ensuite leurs libellés pour renforcer l’interprétabilité. Expérimentée sur un corpus majeur

modèles grands
les biais dans les grands modèles de langage.
Les grands modèles de langage (LLM) pré-entraînés ont

modèles grands
langage.
Les grands modèles de langage (LLM) pré-entraînés ont transformé le traitement du langage naturel (

LLM français
meilleur raisonnement – Repenser les LLM français.
Les grands modèles linguistiques (LLM) ont démontré des capacités

modèles grands
français.
Les grands modèles linguistiques (LLM) ont démontré des capacités remarquables dans diverses tâches de traitement

modèles linguistiques
français.
Les grands modèles linguistiques (LLM) ont démontré des capacités remarquables dans diverses tâches de traitement

modèle grand
connexes et utilise un grand modèle de langage (LLM) pour générer des questions complexes. Des expériences préliminaires

modèles grands
plongements vectoriels de divers grands modèles de langage. Alors que les premiers modèles de type transformeur étaient prin- cipalement

modèles premiers
. Alors que les premiers modèles de type transformeur étaient prin- cipalement axés sur la modélisation thématique, cette étude

modèles grands
à l’aide de grands modèles de langue (LLMs). Les résumés sont évalués en demandant aux LLMs

LLM meilleur
, nous affinons le meilleur LLM sur les résumés générés sélectionnés. Validé sur plusieurs ensembles de données, QUARTZ

modèles grands
hallucinations produites par les grands modèles de langue (LLMs). L’objectif de ce travail est double :

IA générative
L’évaluation des modèles d’IA générative repose sur des datasets contenant des valeurs de référence attendues pour une entrée

intelligence artificielle
à l’ère de l’intelligence artificielle générative.
Cet article présente la genèse, le cadre conceptuel et

intelligence générative
à l’ère de l’intelligence artificielle générative.
Cet article présente la genèse, le cadre conceptuel et

intelligence artificielle
responsable et créatif de l’intelligence artificielle générative (IAg). Issu de consultations et d’expérimentations menées au

intelligence générative
responsable et créatif de l’intelligence artificielle générative (IAg). Issu de consultations et d’expérimentations menées au

modèle multi-tâches
Nous proposons AURA, un modèle multi-tâches combinant prédiction de notes et génération de revues personnalisées. AURA apprend simultanément

modèles avancés
multilingue à l’aide de modèles avancés de traitement automatique du langage naturel. Plus précisément, il étudie l’

modèles grands
également le potentiel des grands modèles de langage génératifs pour la prédiction de la complexité lexicale. À travers différentes

modèles génératifs
également le potentiel des grands modèles de langage génératifs pour la prédiction de la complexité lexicale. À travers différentes

modèles génératifs
que, bien que les modèles génératifs obtiennent des performances prometteuses, leur qualité prédictive reste variable, et les

modèles grands
ressources.

### Composé nominal modifiant une entité-LLM

In [37]:
all_role_nc = set()
all_role_nc_ids = []

for i, row in tqdm(df.iterrows(), total = df.shape[0]):
    llm_entities_ids = row["llm_entities_ids"]
    doc = row["analyzed_text"]

    role_nc_ids = []
    
    for e_id in llm_entities_ids:
        tok = doc[e_id]
        deprel = tok.dep_
        children = tok.children
        
        for child in children:
            if child.dep_ == "nmod" and child.pos_ in ["NOUN", "ADJ"] and list(child.children) == []:
                all_role_nc.add(child.lemma_)
                print(tok, child.orth_)
                print(doc[max(0, e_id-5):min(len(doc), e_id+15)])
                print()

                n_id = get_token_idx(child, doc)
                role_nc_ids.append((e_id, n_id))

    all_role_nc_ids.append(role_nc_ids)

df["noun_compound"] = all_role_nc_ids

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 38766.99it/s]

modèle -
être utilisées pour entraîner un modèle de question-réponse sur un nouveau corpus d’archives numérisées.

modèle réponse
être utilisées pour entraîner un modèle de question-réponse sur un nouveau corpus d’archives numérisées.

LLM -
résultats montrent que seuls les LLM fine-tunés atteignent la précision du modèle de référence. L’analyse des

modèle vanille
améliore de manière significative le modèle BERT vanille de référence. Nous démontrons empiriquement l’efficacité de notre approche par

modèle Base
d’évaluation FLEURS-102. Notre modèle HuBERT Base obtient des résultats similaires face à l’approche multilingue w2v-bert

Llama 8B.
décodeurs causaux, jusqu’à Llama 3 8B.

modèles GPT-2
générées artificiellement en adaptant des modèles GPT-2. Les résultats montrent que les données artificielles ne sont pas encore suffisamment

Mistral Moderation
, dont GPT-4o mini et Mistral Moderation , sur des requêtes multilingues dans des contextes variés. Les résultats montrent

Claude Opus
cette tâche, en particulier Claude 3 Opus. Nous obtenons des résultats similaires pour le SBR et Claude 3

Claude Opus
similaires pour le SBR et Claude 3 Opus lorsqu’il est utilisé conjointement avec notre dictionnaire.

modèle détecteur
d’un document par un modèle détecteur, avec l’hypothèse qu’un faible score de perplexité indique que le

modèle pivot
“PatientDx” utilise un modèle pivot adapté au raisonnement numérique et ajuste les hyperparamètres sur des exemples en fonction

camembert -
ont été utilisés : le camembert-large classique (run 1) et le camembert-large fine-

camembert fine
run 1) et le camembert-large fine-tuné (run 2) sur des articles biomédicaux français

camembert -
run 1) et le camembert-large fine-tuné (run 2) sur des articles biomédicaux français

modèle -
Nous avons également proposé un modèle « bout-enbout », avec une première phase d’extraction d’entités

modèle enbout
Nous avons également proposé un modèle « bout-enbout », avec une première phase d’extraction d’entités

modèle GPT
a été entraîné avec un modèle GPT adapté (Radford et al., 2018), sur un dataset

modèle T5
finale. Implémenté avec le modèle T5 pré-entraîné et une stratégie de réglage par invite, AURA a été testé

modèles CNN
pathologique : étude comparative entre modèles CNN et à base de transformers.
Les cancers des voies aérodigestives supérieures

modèles transformeurs
et sont comparables à des modèles transformeurs biomédicaux affinés sur des données supervisés spécifiques aux problèmes traités. De plus

modèle -
cible. En exploitant le modèle LLaMA 3-8B et des techniques de prompt engineering, ainsi que l’

modèle 8B
cible. En exploitant le modèle LLaMA 3-8B et des techniques de prompt engineering, ainsi que l’

modèles SSL
(CPT) sur des modèles SSL pré-entraînés de deux langues étrangères : la langue lexificatrice – le français –

modèles SSL
les performances de ces trois modèles SSL, et de deux autres modèles SSL étrangers directement affinés, sur une

modèles SSL
, et de deux autres modèles SSL étrangers directement affinés, sur une tâche de reconnaissance de la parole.

modèle WAV2VEC2
. Nous avons entraîné un modèle WAV2VEC2 sur des données multilingues de Maurice, incluant des locuteurs plurilingues et du

modèles seq2seq
capacités de généralisation compositionelle des modèles seq2seq convolutifs (Assessing the Contribution of Syntactic Information for Compositional Generalization of seq2seq

Mistral-7B -
) of different sizes (Mistral-7B-Instruct, Vicuna-13B, and Gemini 1.0 Pro) and to contexts extracted

Gemini Pro
Instruct, Vicuna-13B, and Gemini 1.0 Pro) and to contexts extracted from articles web-crawled from specialised

modèle L_S
modèle, TestOnSource où un modèle L_S est couplé avec des modules de traduction au moment du décodage et TrainOnSourceAdaptOnTarget

Llama3.0 -
standards : ChatGPT-4o mini ,Llama3.0-8B ,Llama3.1-8B etQwen2.5-14B . En moyenne, ChatGPT

Llama3.0 8B
standards : ChatGPT-4o mini ,Llama3.0-8B ,Llama3.1-8B etQwen2.5-14B . En moyenne, ChatGPT

Llama3.1 -
,Llama3.0-8B ,Llama3.1-8B etQwen2.5-14B . En moyenne, ChatGPT et la série Llama

Llama3.1 8B
,Llama3.0-8B ,Llama3.1-8B etQwen2.5-14B . En moyenne, ChatGPT et la série Llama

etQwen2.5 -
8B ,Llama3.1-8B etQwen2.5-14B . En moyenne, ChatGPT et la série Llama obtiennent une précision

etQwen2.5 14B
8B ,Llama3.1-8B etQwen2.5-14B . En moyenne, ChatGPT et la série Llama obtiennent une précision

agents LLMs
renforcement pour l’alignement des agents LLMs avec des environnements interactifs : quantification et réduction du surapprentissage aux prompts.

Llama-3.3 70B
en utilisant quatre LLM (Llama-3.3 70B, DeepSeek R1 70B, Qwen 72B, Gemma 3 27B) et

DeepSeek R1
LLM (Llama-3.3 70B, DeepSeek R1 70B, Qwen 72B, Gemma 3 27B) et plusieurs températures de

DeepSeek 70B
LLM (Llama-3.3 70B, DeepSeek R1 70B, Qwen 72B, Gemma 3 27B) et plusieurs températures de

Gemma 27B
70B, Qwen 72B, Gemma 3 27B) et plusieurs températures de génération. Nos résultats indiquent que la

modèles encodeurs
, à l’instar des modèles encodeurs. Ainsi, nous proposons une approche de génération augmentée par recherche d’

modèles -
, obtenus sur de petits modèles de langue fine-tunés sur des données de conversations parlées en français et

modèle Pre
adaptation en français du fameux modèle Generative Pre-trained Transformer (GPT). Ce dernier appartient à la

CamemBERT bio
CamemBERT-bio : Un modèle de langue français savoureux et meilleur pour la santé

agents -
. En nous intéressant aux agents conversationnels génératifs orientés-tâches, nous proposons une nouvelle approche pour rendre la

agents tâches
. En nous intéressant aux agents conversationnels génératifs orientés-tâches, nous proposons une nouvelle approche pour rendre la

modèles Instruct
les premiers résultats sur des modèles Instruct généralistes multilingues en comparant les performances du corpus original en anglais à celles

agent LLM
sur BERT et sur l’agent LLM pour la classification hiérarchique de narratifs dans les articles de presse multilingues.

agents LLM
. La seconde utilise des agents LLM spécialisés, chacun effectuant une classification binaire pour des catégories narratives spécifiques.

### Compléments du nom associés à une entité-LLM

In [38]:
all_gen_nc = set()
all_gen_nc_ids = []

for i, row in tqdm(df.iterrows(), total = df.shape[0]):
    llm_entities_ids = row["llm_entities_ids"]
    doc = row["analyzed_text"]

    gen_nc_ids = []
    
    for e_id in llm_entities_ids:
        tok = doc[e_id]
        deprel = tok.dep_
        head = tok.head
        children = tok.children

        if deprel == "nmod" and head.pos_ == "NOUN":
            case_children = [child.lemma_ for child in children if child.dep_ == "case" and "d" in child.orth_]
            
            if any(case_children):
                all_gen_nc.add(head.lemma_)
                print(head.lemma_, case_children, tok)
                print(doc[max(0, e_id-5):min(len(doc), e_id+15)])
                print()

                head_id = get_token_idx(head, doc)
                gen_nc_ids.append((head_id, e_id))
    
    all_gen_nc_ids.append(gen_nc_ids)        

df["compl_noms"] = all_gen_nc_ids

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 21739.63it/s]

intégration ['dans'] modèles
du raisonnement numérique dans les modèles de langue : État de l’art et direction de recherche.
Ces

intégration ['dans'] modèles
du raisonnement numérique dans les modèles de langue a suscité un intérêt grandissant. Pourtant, bien que l’entraînement

entraînement ['de'] modèles
bien que l’entraînement des modèles de langue sur des données numériques soit devenu un paradigme courant, les modèles

travail ['dans'] modèles
le raisonnement numérique dans les modèles de langue et dans un second temps nous discutons des différentes perspectives de recherche

compétence ['de'] modèles
augmenter les compétences numériques des modèles.

utilisation ['dans'] agents
à leur utilisation dans des agents conversationnels incarnés ou dans d’autres domaines de recherche comme la linguistique, où

représentation ['dans'] modèles
représentations contextuelles stéréotypées dans les modèles de langue français : mieux les identifier pour ne pas les reproduire.


capacité ['de'] modèles
entre les capacités linguistiques des modèles et la présence de biais mesurables. Nous étendons notre étude en examinant des

tuning ['de'] CamemBERT
le fine-tuning de CamemBERT, une approche hybride combinant CamemBERT et des variables linguistiques et des modèles de

analyse ['de'] modèles
Une analyse approfondie de ces modèles et de leurs performances est menée afin d’évaluer leur applicabilité dans des contextes

domaine ['de'] modèles
notables dans le domaine des modèles de langage neuronaux. Malgré ces avancées, cette tâche reste difficile quand il

ère ['de'] ChatGPT
antérieurs à l’ère de ChatGPT, que les textes générés par des outils tels que ChatGPT partagent certaines caractéristiques

base ['de'] modèles
règles et à base de modèles de langue. Les données ont ensuite été ajoutées de manière itérative pour affiner

fonction ['de'] modèle
, et en fonction du modèle de langue utilisé. Cette étude met également en évidence que l’augmentation de

découverte ['de'] intelligence
Découverte de l’intelligence artificielle par des directeurs et directrices d’école primaire : une étude de cas

intelligence ['de'] IA
, en particulier de l’IA générative, dans le cadre du numérique éducatif et de la transformation digitale de

évolution ['de'] IA
l’évolution historique de l’IA, ses fondements ainsi que ses applications pédagogiques. Les résultats, issus de

technologie ['d’'] IA
initiale limitée des technologies d’IA, les participants ont manifesté un intérêt croissant pour l’exploration de ces outils

intégration ['de'] IA
une intégration responsable de l’IA en éducation.

entraînement ['de'] modèles
Vers l’entraînement de modèles de reconnaissance automatique de la parole auto-supervisés équitables sans étiquettes démographiques.
Malgré

performance ['de'] modèles
comparons les performances de plusieurs modèles d’extraction et de génération de mots-clés appliqués aux résumés d’articles issus des

performance ['de'] LLMs
pour évaluer les performances des LLMs en tenant compte des coûts de traitement, offrant ainsi une perspective équilibrée entre

entraînement ['de'] modèles
et l’évaluation de ces modèles se concentrent sur un nombre restreint de domaines et types de documents (articles

performance ['d’'] modèle
, les performances d’un modèle entraîné sur un domaine ciblé sont en général moindres dans un autre : ceux

mise ['dans'] Modèles
des Connaissances Factuelles dans les Modèles de Langue Causaux.
La factualité des modèles de langue se dégrade avec

factualité ['de'] modèles
.
La factualité des modèles de langue se dégrade avec le temps puisque les événements postérieurs à leur entraînement

connaissance ['dans'] modèles
Connaissances factuelles dans les modèles de langue : robustesse et anomalies face à des variations simples du contexte temporel

robustesse ['de'] modèles
papier explore la robustesse des modèles de langue (ML) face aux variations du contexte temporel dans les connaissances

adaptation ['de'] modèles
l’adaptation non supervisée de modèles de compréhension de documents (Question generation from semantic analysis for unsupervised adaptation of

facteur ['de'] modèles
des facteurs de complexité des modèles de langage dans une tâche de compréhension de lecture à l’aide d’une

dimension ['de'] modèles
indépendamment de la dimension des modèles. Il montre que la performance inférieure de certains exemples est attribuable à des

taille ['de'] modèles
augmentation de la taille des modèles.

réentrainement ['de'] modèle
de données de réentrainement du modèle de rapprochement sémantique. Nous proposons une approche différente, impactant le score des

contexte ['de'] modèles
AA dans le contexte des modèles de langues pré-entraînés.De plus, le mécanisme de fine-

standardisation ['de'] IA
européen de standardisation de l’IA en matière de TALN. Le comité CEN-CENELEC JTC 21 a été

volet ['de'] IA
un volet spécifique de l’IA, méritant ses propres outils, critères et bonnes pratiques. Ce constat a

utilisation ['de'] modèles
. L’utilisation de ces modèles permet d’encoder contextuellement du texte afin de l’utiliser dans des réseaux neuronaux

utilisation ['de'] CamemBERT
basant sur l’utilisation de CamemBERT. Dans un premier temps, uniquement du texte provenant de documents médicaux a

apport ['de'] modèles
apport au niveau linguistique de modèles de langage utilisés pour le réordonnancement d’hypothèses de transcription a posteriori.

capacité ['de'] modèles
étude sur la capacité des modèles de langues à évaluer la prise de parole en public.
L’importance

intégration ['de'] modèles
mais l’intégration des grandes modèles de langue (LLMs) reste peu explorée. Nous proposons un cadre où

limite ['de'] LLMs
soulignant les limites actuelles des LLMs pour l’analyse de la PPP. Code source et données disponibles sur GitHub

taille ['de'] modèles
restriction sur la taille des modèles de langue. Les résultats, mesurés par l’Exact Match Ratio (EMR

adaptation ['de'] modèles
Adaptation des modèles de langue à des domaines de spécialité par un masquage sélectif fondé sur le

caractéristique ['de'] modèles
(TALN).Une des caractéristiques des modèles reposant sur une architecture Transformeur concerne la stratégie de masquage utilisée pour capturer les

performance ['de'] modèles
document.Les performances des modèles résultant d’un pré-entraînement continu dans le domaine juridique soulignent l’efficacité de notre

adaptation ['de'] modèles
sur l’adaptation des grands modèles de langue (LLMs) à des domaines spécialisés disposant de données limitées.

adaptation ['d’'] modèle
que l’adaptation d’un modèle généraliste à de nouvelles données dans le domaine médical offre des améliorations notables (

adaptation ['de'] modèles
que l’adaptation supplémentaire de modèles déjà familiarisés avec ce domaine procure des bénéfices limités. Bien que CPT+SFT offre

capacité ['de'] modèles
en détail la capacité des modèles à transcrire les spécificités métiers, nous effectuons une analyse plus fine sur les

aide ['d’'] modèle
à l’aide d’un modèle entraîné sur des corpus traduits à l’aide des langues pivot et cible.

adaptation ['de'] modèles
Adaptation de modèles auto-supervisés pour la reconnaissance de phonèmes dans la parole d’enfant.
La

comportement ['de'] modèles
les comportements de ces deux modèles en conditions réelles de notre application, et montrons que WavLM base+ est plus

emploi ['de'] Modèles
ici l’emploi de Grands Modèles de Langages (LLM) pour structurer les textes de posologie en comparant des

tuning ['de'] LLM
le fine-tuning de LLM avec un système “pré-LLM” fondé sur un algorithme de reconnaissance et liaison

précision ['de'] modèle
tunés atteignent la précision du modèle de référence. L’analyse des erreurs révèle une complémentarité des deux approches :

utilisation ['d’'] LLM
détaillons l’utilisation d’un LLM dans le développement de NuNER, un modèle d’encodage du texte, compact

famille ['de'] modèles
partie de la famille des modèles de fondation spécialisés. L’intérêt de NuNER est qu’il ne nécessite que

intérêt ['de'] modèles
Intérêt des modèles de caractères pour la détection d’événements (The interest of character-level

biais ['de'] modèles
compte par le biais de modèles de caractères, nous proposons d’intégrer des plongements de caractères, qui peuvent

aide ['de'] Modèles
l’aide de « Larges Modèles de Langue ».
Ce papier présente la participation d’EDF R&D à

instar ['de'] BERT
) à l’instar de BERT se sont révélés remarquablement efficaces pour le classement ad hoc. Contrairement aux modèles

domaine ['de'] modèles
Adaptation au domaine de modèles de langue à l’aide de réseaux à base de graphes (Graph Neural

étude ['de'] modèle
phrase : une étude du modèle LenInit (Investigating Length Regulation in a Sentence Compression Neural System : a Study

cas ['de'] modèle
étudiant spécifiquement le cas du modèle LenInit. Notre analyse met en évidence la coexistence de deux influences distinctes au

explicabilité ['de'] modèles
Utiliser l’explicabilité des modèles pour mettre en évidence les expressions genrées dans la parole.
Dans de

explicabilité ['de'] Modèles
”, Explicabilité Globale des Modèles de TAL par la Génération Coopérative.
L’omniprésence de l’apprentissage automatique

type ['de'] modèle
méthodes agnostiques au type de modèle génèrent des exemples artificiels en modifiant légèrement les données originales. Elles observent ensuite

décision ['de'] modèle
les changements de décision du modèle sur ces exemples artificiels. Cependant, de telles méthodes nécessitent d’avoir des

fonctionnement ['de'] modèle
sur le fonctionnement global du modèle au lieu de plusieurs explications locales, offrant ainsi une vue d’ensemble du

fonctionnement ['de'] modèle
d’ensemble du fonctionnement du modèle. Nos expériences montrent que, même sans données en entrée, Therapy fournit

distribution ['de'] modèle
échantillonnage de la distribution du modèle de langue vers des textes ayant la propriété attendue. Dans cet article,

alignement ['dans'] modèles
attention et sémantique dans des modèles de langues pré-entraînés.
Les AMR (Abstract Meaning Representation) sont une

mécanisme ['d’'] modèle
mécanisme d’attention d’un modèle de langue (ML) peut être modélisé comme le calcul de vecteurs descripteurs

apport ['d’'] modèle
analyser les apports d’un modèle de langue pré-entraîné de type BERT (bidirectional encoder representations from transformers) à

apport ['de'] BERT
que malgré l’apport de BERT à la qualité des analyses (jusqu’à 95 en F1 ), certains

usage ['de'] LLM
à améliorer l’usage des LLM pour la recherche d’informations scientifiques.

exception ['de'] modèles
, à l’exception des modèles de petite taille. L’ensemble de notre protocole d’évaluation est entièrement reproductible

diffusion ['de'] modèles
du grand public de grands modèles de langue facilite la production de contenus nuisibles, médisants, malhonnêtes ou falsifiés

paire ['de'] modèles
sur une paire fixe de modèles peut fragiliser les performances. Nous étendons ces méthodes en combinant plusieurs modèles et

évaluation ['dans'] modèles
biais de genre dans des modèles de langue auto-régressifs.
Nous proposons un outil pour mesurer automatiquement les biais

définition ['d’'] modèle
de la définition d’un modèle de langue « idéal » et des moyens d’y parvenir.

évaluation ['de'] Modèles
et l’alignement des Grands Modèles de Langue (LLM) sur des questions politiques sont devenus des préoccupations cruciales

pré-entraînement ['de'] BERT
? Stratégies de pré-entraînement de BERT en domaine médical (Re-train or train from scratch ? Pre-training strategies

performance ['d’'] modèle
peu la performance d’un modèle BERT lorsque celui-ci est ré-entraîné sur un corpus médical.

transfert ['de'] modèles
la capacité de transfert des modèles de classification de texte dans le domaine journalistique, en particulier pour distinguer les

type ['de'] modèles
et évaluer deux types de modèles : CamemBERT (Martin et al., 2019), un modèle neuronal

version ['de'] modèle
Dix versions différentes de chaque modèle sont entraînées : 8 versions mono-médias’, chacune peaufinée sur l’ensemble d’entraînement

généricité ['de'] modèle
sources améliore la généricité du modèle. Les modèles statistiques (mono- et multi-médias) montrent des performances globalement inférieures

supériorité ['de'] modèles
étude démontre la supériorité des modèles neuronaux comme CamemBERT pour la classification de textes journalistiques, notamment grâce à leur

sous-espace ['de'] modèles
l’apprentissage de sous-espaces de modèles. Cette méthode, permettant de trouver non pas un point minimum local de

paramètre ['de'] modèle
l’espace des paramètres du modèle, mais tout un simplexe associé à des valeurs basses, présente typiquement des

ajustement ['d’'] modèle
de l’ajustement d’un modèle par l’inférence d’une métrique de validation, problématique d’actualité en “

sous-espace ['de'] modèles
l’ajustement de sous-espaces de modèles est empiriquement associée à un gain considérable en performances de généralisation sur les tâches

propriété ['de'] modèles
pour étudier les propriétés des modèles de langue contextuels mais, de manière surprenante, seules quelques-unes d’

propriété ['de'] modèles
sur les propriétés de ces modèles en termes de similarité sémantique. Dans cet article, nous proposons d’abord

propriété ['de'] modèles
explorer les propriétés sémantiques des modèles ELMo et BERT du point de vue des relations paradigmatiques de WordNet et dans

plan ['de'] modèles
vraiment sur ce plan de modèles plus anciens, comme les modèles statiques ou les modèles à base de comptes

nombre ['de'] modèles
d’un nombre important de modèles de langue neuronaux affinés pour différentes tâches conduit assez naturellement à se poser la

fusion ['de'] modèles
méthode pour la fusion de modèles affinés pour une même tâche à partir d’un même modèle de base,

plongement ['dans'] modèles
statistique des plongements dans les modèles transformers pour le français (An empirical statistical study of embeddings in French transformers

plongement ['dans'] modèles
statistiques des plongements dans les modèles transformers pour le français. Nous nous appuyons sur une analyse de la variance

comportement ['de'] modèles
textes modifie le comportement des modèles, notamment dans les dernières couches, et procure une tendance forte à l’

transfert ['de'] modèles
Transfert de modèles de langue pour la classification rhétorique des citations à travers les disciplines.


transfert ['de'] modèles
les capacités de transfert des modèles de langue affinés en linguistique computationnelle pour cette tâche, en les comparant aux

sensibilité ['de'] modèles
explorons également la sensibilité des modèles aux longueurs des contextes des passages de citations. Nos résultats montrent de bonnes

performance ['de'] modèles
montrent de bonnes performances des modèles de langue transférés en écologie et l’intérêt de réviser la typologie pour évaluer

fusion ['de'] modèles
PatientDx : Fusion des grands modèles de langue pour la protection de la confidentialité des données dans le domaine de

affinage ['de'] modèles

L’affinage des grands modèles de langue (abrégé LLM de l’anglais large language model) est devenu

performance ['de'] modèles
pour améliorer la performance des modèles sur une tâche donnée. Cependant, cette amélioration de performance s’accompagne d’

fusion ['de'] modèles
une architecture de fusion de modèles permettant de concevoir des LLM efficaces pour les tâches prédictives en santé sans nécessiter

fusion ['de'] LLM
le nom de fusion de LLM et vise à optimiser une stratégie de fusion modulaire. “PatientDx” utilise

utilisation ['de'] modèles
article explore l’utilisation des modèles de langage multimodaux, en particulier GPT-4o, pour l’interprétation automatisée de cartes

capacité ['de'] modèle
pour évaluer la capacité du modèle à répondre à des questions fermées, selon différentes stratégies de génération. Malgré

limite ['de'] modèles
évidence les limites actuelles des modèles multimodaux pour l’analyse cartographique, et souligne la nécessité de recherches fondamentales et

intégration ['dans'] modèles
du genre discursif dans les modèles de prédiction de la lisibilité. En utilisant des architectures neuronales basées sur CamemBERT

performance ['de'] modèles
avons comparé les performances de modèles intégrant l’information de genre à celles d’un modèle de base ne considérant

conception ['de'] modèles
lors de la conception de modèles de lisibilité et de traiter le genre comme une information riche à laquelle le

système ['d’'] intelligence
équité dans les systèmes d’intelligence artificielle, nous nous intéressons aux pratiques actuelles lors des grandes campagnes d’évaluation

essor ['de'] intelligence
Avec l’essor de l’intelligence artificielle (IA) et l’utilisation croissante des architectures d’apprentissage profond,

système ['d’'] IA
la transparence des systèmes d’IA est devenue une préoccupation centrale au sein de la communauté de recherche. Dans

véracité ['de'] modèles
Évaluer la véracité des grands modèles de langage (LLMs) est essentiel pour de nombreuses applications. Cependant,

performance ['de'] modèle
runs. La performance du modèle « bout-en-bout » est similaire aux autres méthodes.

performance ['de'] ChatGPT
impact sur les performances de ChatGPT.

robustesse ['de'] LLM
Évaluation de la Robustesse des LLM : Proposition d’un Cadre Méthodologique et Développement d’un Benchmark.
L’

évaluation ['de'] modèles
L’évaluation fiable des grands modèles de langage (LLM) demeure un défi. Nous présentons un framework systématique

stabilité ['de'] LLM
pour tester la stabilité des LLM. Les réponses sont évaluées par une double approche automatique (LLM-as

comparaison ['de'] LLM
plus transparente et équitable des LLM.

réplique ['de'] agent
donne la réplique de l’agent. Il lui arrive malgré tout de manquer de cohérence dans la réponse.

aide ['de'] modèles
phrases à l’aide de modèles de langues pré-entraînés, aboutissant au clustering de ces vecteurs pour construire des regroupements

signal ['de'] Modèles
des Signaux Contextuels Multi-niveaux des Modèles de Langue Préentraînés.
L’accès croissant aux documents juridiques sous format numérique

couche ['de'] modèles
exploitant les couches intermédiaires des modèles du Transformer afin d’améliorer la représentation des documents juridiques. En particulier,

utilisation ['de'] LLM
contre l’utilisation croissante des LLM dans l’évaluation, en soulignant leur nature stochastique, leur dépendance technique et

étude ['dans'] modèles
les biais dans les grands modèles de langage.
Les grands modèles de langage (LLM) pré-entraînés ont

biais ['de'] LLM
recherches sur les biais des LLM, identifie les lacunes concernant les déterminants sociaux de la santé (DSS)

intégration ['de'] LLM
améliorant l’intégration sécurisée des LLM en santé.

langue ['d’'] LLM
la langue française d’un LLM. Nous démontrons des améliorations du raisonnement mathématique en utilisant seulement 2000 échantillons soigneusement

dispersion ['de'] modèles
la dispersion vectorielle de différents modèles de langage.
Cet article vise à étudier comment le style d’écriture

plongement ['de'] modèles
plongements vectoriels de divers grands modèles de langage. Alors que les premiers modèles de type transformeur étaient prin- cipalement

sensibilité ['de'] modèles
nous comparons la sensibilité des modèles de langage en français et en anglais. En analysant ainsi l’impact spécifique

entraînement ['de'] modèles
souvent sur l’entraînement de modèles de langue à imiter des résumés humains. Cependant, cette approche est coûteuse

aide ['de'] modèles
à l’aide de grands modèles de langue (LLMs). Les résumés sont évalués en demandant aux LLMs

hallucination ['de'] LLMs
et mitigation des hallucinations des LLMs.
Cet article présente un état de l’art sur les hallucinations produites

évaluation ['de'] modèles
.

In [39]:
# Sauvegarde des modifications apportées aux données

# with open(os.path.join(data_folder, processed_jeptalnrecital_file_path) + ".pkl", "wb") as f:
#     pickle.dump(df, f)

# with open(os.path.join(data_folder, processed_jeptalnrecital_file_path) + ".pkl", "rb") as f:
#     df = pickle.load(f)